Repository mosn/layotto, pull requests merged in 2021-09, with the labels that each got.

#204 Translate chinese documents into english for issue #202
  docs/_sidebar.md
  docs/en/development/contributing-doc.md
  docs/en/development/developing-api.md
  docs/en/development/developing-component.md
Labels: documentation, cla:yes, size/L

#208 style: replace `go func` with `utils.GoWithRecover`
  components/configstores/apollo/change_listener.go
  pkg/grpc/api.go
  sdk/go-sdk/client/client_test.go
  sdk/go-sdk/client/configuration.go
  sdk/go-sdk/client/goroutine.go
  sdk/go-sdk/client/goroutine_test.go
Labels: cla:yes, size/L, First-time contributor

#209 add trace for layotto
  components/configstores/etcdv3/etcdv3.go
  components/go.mod
  components/hello/hello.go
  components/hello/helloworld/helloworld.go
  components/trace/export.go
  components/trace/export_test.go
  components/trace/generator.go
  components/trace/generator_test.go
  components/trace/span.go
  components/trace/types.go
  components/trace/utils.go
  components/trace/utils_test.go
  configs/runtime_config.json
  demo/go.sum
  diagnostics/exporter_iml/stdout.go
  diagnostics/genetator.go
  diagnostics/grpc_tracing.go
  diagnostics/tracing.go
  docs/_sidebar.md
  docs/en/start/trace/trace.md
  docs/img/trace/trace.png
  docs/zh/_sidebar.md
  docs/zh/start/trace/trace.md
  go.mod
  go.sum
  pkg/grpc/api.go
  pkg/grpc/grpc.go
  pkg/mock/hello.go
Labels: cla:yes, size/XL

#211 optimize
  components/rpc/invoker/mosn/channel/connpool.go
  components/rpc/invoker/mosn/channel/xchannel.go
  components/rpc/invoker/mosn/transport_protocol/bolt.go
  components/rpc/invoker/mosn/transport_protocol/protocol.go
Labels: cla:yes, size/M

#210 refactor: format java-sdk code
  sdk/java-sdk/src/main/java/spec/sdk/reactor/v1/CoreCloudRuntimes.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/RPCClient.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/RuntimeClient.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/client/RuntimesClient.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/ConfigurationRuntimes.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/DeleteStateRequest.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/GetBulkStateRequest.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/GetStateRequest.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/HelloRuntimes.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/InvocationRuntimes.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/PubSubRuntimes.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/SaveStateRequest.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/StateOptions.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/StateRuntimes.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/state/DeleteStateRequest.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/state/ExecuteStateTransactionRequest.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/state/GetBulkStateRequest.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/state/GetStateRequest.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/state/SaveStateRequest.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/state/State.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/state/StateOptions.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/state/TransactionalStateOperation.java
  sdk/java-sdk/src/main/java/spec/sdk/runtime/v1/domain/state/TransactionalStateRequest.java
Labels: cla:yes, size/XL, First-time contributor

#118 Add oss support
  cmd/layotto/main.go
  components/file/alicloud/oss/oss.go
  components/file/alicloud/oss/oss_test.go
  components/file/file.go
  components/file/registry.go
  components/file/types.go
  components/go.mod
  components/go.sum
  configs/config_file.json
  demo/file/client.go
  demo/file/stressmem.go
  demo/go.mod
  docs/_sidebar.md
  docs/en/api_reference/file/file.md
  docs/en/component_specs/file/oss.md
  docs/img/file/put.png
  docs/zh/README.md
  docs/zh/_sidebar.md
  docs/zh/api_reference/file/file.md
  docs/zh/component_specs/file/oss.md
  docs/zh/design/file/file-design.md
  go.mod
  go.sum
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/mock/file.go
  pkg/mock/runtime.pb.go
  pkg/runtime/config.go
  pkg/runtime/options.go
  pkg/runtime/runtime.go
  sdk/go-sdk/client/client.go
  spec/go.mod
  spec/go.sum
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL

#215 add attrs
  components/trace/types.go
  diagnostics/genetator.go
  diagnostics/tracing.go
Labels: cla:yes, size/S

#219 Ignore the build result
  .gitignore
Labels: size/XS, cla:yes, First-time contributor

#220 Ignore the redis demo binary
  .gitignore
Labels: size/XS, cla:yes

#223 fix errors in wasm quick start doc
  docs/en/start/wasm/start.md
  docs/zh/start/wasm/start.md
Labels: bug, cla:yes, size/S

#225 upgrade_proxy_wasm_sdk
  demo/go.mod
  demo/go.sum
  demo/wasm/code/golang/wasm.go
  demo/wasm/code/golang/wasm_1_1.wasm
  demo/wasm/code/golang/wasm_1_2.wasm
  demo/wasm/code/golang/wasm_2.wasm
  demo/wasm/code/golang/wasm_2_reload.wasm
  go.mod
  go.sum
  pkg/wasm/abi.go
  pkg/wasm/factory.go
Labels: cla:yes, size/M

#229 fix broken markdown in docs
  docs/en/start/wasm/start.md
  docs/zh/start/wasm/start.md
Labels: bug, cla:yes, size/S

#227 refact file interface
  components/file/alicloud/oss/oss.go
  components/file/alicloud/oss/oss_test.go
  components/file/file.go
  components/file/types.go
  demo/file/client.go
  demo/file/stressmem.go
  demo/pubsub/redis/client/publish_client.go
  demo/pubsub/redis/server/subscribe_server.go
  diagnostics/genetator.go
  diagnostics/grpc_tracing.go
  docs/en/api_reference/file/file.md
  docs/zh/api_reference/file/file.md
  docs/zh/design/file/file-design.md
  go.mod
  go.sum
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/mock/file.go
  pkg/runtime/config_test.go
Labels: cla:yes, size/L

#203 add community governance rules and membership list
  docs/img/community/img.png
  docs/img/community/img2.png
  docs/zh/_sidebar.md
  docs/zh/community/governance.md
  docs/zh/community/people.md
  docs/zh/community/promote.md
  docs/zh/development/developing-api.md
Labels: cla:yes, size/L

#233 add bindings for layotto
  cmd/layotto/main.go
  components/go.mod
  components/go.sum
  configs/config_bindings.json
  demo/bindings/main.go
  go.mod
  go.sum
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/messages/api_errors.go
  pkg/mock/components/state/state.go
  pkg/runtime/bindings/factory.go
  pkg/runtime/bindings/metadata.go
  pkg/runtime/bindings/registry.go
  pkg/runtime/bindings/registry_test.go
  pkg/runtime/config.go
  pkg/runtime/options.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  spec/go.mod
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL

#230 Feature/add rpc anno
  components/rpc/callback/callback.go
  components/rpc/callback/dubbo_json_rpc.go
  components/rpc/invoker/mosn/channel/channel.go
  components/rpc/invoker/mosn/channel/connpool.go
  components/rpc/invoker/mosn/channel/httpchannel.go
  components/rpc/invoker/mosn/channel/xchannel.go
  components/rpc/invoker/mosn/mosninvoker.go
  components/rpc/invoker/mosn/transport_protocol/bolt.go
  components/rpc/invoker/mosn/transport_protocol/dubbo.go
  components/rpc/invoker/mosn/transport_protocol/protocol.go
  components/rpc/registry.go
  components/rpc/types.go
Labels: cla:yes, size/L, First-time contributor

#237 Fix security
  components/go.mod
  components/go.sum
  demo/bindings/main.go
  demo/go.mod
  demo/go.sum
  go.mod
  go.sum
Labels: bug, cla:yes, size/XL

#239 Fix security
  components/go.mod
  components/go.sum
  go.sum
Labels: bug, cla:yes, size/L
