Repository mosn/layotto, pull requests merged in 2021-12, with the labels that each got.

#325 feat(java-sdk): java sdk support File API
  sdk/java-sdk/README-zh.md
  sdk/java-sdk/README.md
  sdk/java-sdk/examples/pom.xml
  sdk/java-sdk/examples/src/main/java/io/mosn/layotto/examples/file/File.java
  sdk/java-sdk/pom.xml
  sdk/java-sdk/sdk/pom.xml
  sdk/java-sdk/sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/FileRuntime.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/DelFileRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/DelFileResponse.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/FileInfo.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetFileRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetFileResponse.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetMetaRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetMeteResponse.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/ListFileRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/ListFileResponse.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/PutFileRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/PutFileResponse.java
  sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/FileTest.java
  sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/FileTestWithRealServer.java
  sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/mock/MyFileService.java
Labels: cla:yes, size/XXL, First-time contributor

#231 Double buffer for sequencer catch
  go.mod
  go.sum
  pkg/grpc/api.go
  pkg/runtime/runtime.go
  pkg/runtime/sequencer/cache.go
  pkg/runtime/sequencer/catch_test.go
  pkg/runtime/sequencer/sequencer_config.go
  pkg/runtime/sequencer/sequencer_config_test.go
  pkg/runtime/sequencer/utils.go
Labels: cla:yes, size/XL

#351 add share videos
  docs/zh/_sidebar.md
  docs/zh/video/a-new-chapter-in-service-mesh-application-runtime.md
  docs/zh/video/inject-soul-into-sidecar.md
Labels: size/XS, cla:yes

#356 feat(java-sdk): java sdk support File API (#325)
  sdk/java-sdk/README-zh.md
  sdk/java-sdk/README.md
  sdk/java-sdk/examples/pom.xml
  sdk/java-sdk/examples/src/test/java/io/mosn/layotto/examples/file/File.java
  sdk/java-sdk/pom.xml
  sdk/java-sdk/sdk/pom.xml
  sdk/java-sdk/sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/FileRuntime.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/DelFileRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/DelFileResponse.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/FileInfo.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetFileRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetFileResponse.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetMetaRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetMeteResponse.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/ListFileRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/ListFileResponse.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/PutFileRequest.java
  sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/PutFileResponse.java
  sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/FileTest.java
  sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/FileTestWithRealServer.java
  sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/mock/MyFileService.java
Labels: cla:yes, size/XXL, First-time contributor

#299 feat: fix minio default bucket and add quick start doc
  components/file/s3/minio/oss_test.go
  components/go.sum
  configs/config_file.json
  demo/go.mod
  demo/go.sum
  docs/img/file/minio.png
  docs/zh/_sidebar.md
  docs/zh/start/file/minio.md
  docs/zh/start/file/start.md
  go.sum
Labels: bug, cla:yes, size/XL

#333 fix: fix in-mem component issues
  README.md
  cmd/layotto/main.go
  docs/en/README.md
  docs/zh/README.md
  go.mod
  pkg/mock/components/state/in_memory.go
  pkg/mock/components/state/in_memory_test.go
Labels: bug, cla:yes, size/L

#364 fix zk lock ut
  components/lock/zookeeper/zookeeper_lock_test.go
Labels: bug, cla:yes, size/S

#348 add mongo distributed lock
  cmd/layotto/main.go
  components/go.mod
  components/go.sum
  components/lock/mongo/mongo_lock.go
  components/lock/mongo/mongo_lock_test.go
  components/pkg/utils/mongo.go
  components/pkg/utils/mongo_lock_mock.go
  configs/config_lock_mongo.json
  demo/lock/mongo/client.go
  docs/_sidebar.md
  docs/en/component_specs/lock/mongo.md
  docs/zh/component_specs/lock/mongo.md
  go.sum
  sdk/go-sdk/go.mod
  sdk/go-sdk/go.sum
Labels: cla:yes, size/XXL

#366 fix Incorrect conversion
  components/file/local/file.go
Labels: bug, size/XS, cla:yes

#367 test components and sdk package in CI pipeline
  .github/workflows/github-actions.yml
  Makefile
  components/lock/redis/cluster_redis_lock_test.go
  components/lock/redis/standalone_redis_lock.go
  components/lock/redis/standalone_redis_lock_test.go
  components/rpc/types_test.go
  components/sequencer/etcd/store_test.go
  etc/script/report.sh
  pkg/actuator/actuator_test.go
  pkg/converter/state_test.go
  pkg/runtime/runtime_test.go
  pkg/runtime/sequencer/cache_test.go
Labels: cla:yes, size/L

#372 fix package testing/fstest is not in GOROOT of golang1.14
  components/go.mod
  components/go.sum
  go.mod
  go.sum
Labels: bug, cla:yes, size/M

#370 add comment of wasm
  pkg/wasm/abi.go
  pkg/wasm/config.go
  pkg/wasm/dispatch.go
  pkg/wasm/factory.go
  pkg/wasm/filter.go
  pkg/wasm/imports.go
  pkg/wasm/watcher.go
Labels: cla:yes, size/M

#373 test: improve test cases for consul lock
  codecov.yml
  components/lock/consul/consul_lock.go
  components/lock/consul/consul_lock_task.go
  components/lock/consul/consul_lock_test.go
Labels: cla:yes, size/M

#368 upgrade mosn v0.26.0, which refactory the xprotocol
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  components/go.mod
  components/go.sum
  components/rpc/invoker/mosn/channel/xchannel_test.go
  components/rpc/invoker/mosn/transport_protocol/bolt.go
  components/rpc/invoker/mosn/transport_protocol/bolt_test.go
  components/rpc/invoker/mosn/transport_protocol/dubbo.go
  components/rpc/invoker/mosn/transport_protocol/protocol.go
  components/trace/span.go
  diagnostics/genetator.go
  diagnostics/tracing.go
  go.mod
  go.sum
  pkg/grpc/dapr/dapr_api.go
Labels: cla:yes, size/L

#369 feat: make parameters of API plugin extendable
  .github/workflows/github-actions.yml
  cmd/layotto_multiple_api/helloworld/grpc_api.go
  cmd/layotto_multiple_api/main.go
  codecov.yml
  components/rpc/callback/callback.go
  components/rpc/invoker/mosn/channel/connpool.go
  components/rpc/invoker/mosn/channel/httpchannel.go
  components/rpc/invoker/mosn/channel/xchannel.go
  components/rpc/invoker/mosn/mosninvoker.go
  components/rpc/types.go
  pkg/actuator/info/endpoint.go
  pkg/actuator/info/endpoint_test.go
  pkg/grpc/dapr/dapr_api.go
  pkg/grpc/dapr/dapr_api_test.go
  pkg/grpc/default_api/api.go
  pkg/grpc/grpc_api.go
  pkg/runtime/runtime.go
Labels: cla:yes, size/L
