Repository mosn/layotto, pull requests merged in 2021-11, with the labels that each got.

#245 add license file for file
  components/file/alicloud/oss/oss.go
  components/file/alicloud/oss/oss_test.go
  components/file/file.go
  components/file/registry.go
  components/file/types.go
  demo/file/client.go
  demo/file/stressmem.go
  docs/en/building_blocks/file/file.md
  docs/en/component_specs/file/oss.md
  docs/img/file/img.png
  docs/zh/_sidebar.md
  docs/zh/building_blocks/file/file.md
  docs/zh/component_specs/file/common.md
  docs/zh/design/file/file-design.md
  docs/zh/start/file/start.md
Labels: cla:yes, size/XL

#304 add English presentations
  README.md
  docs/en/README.md
Labels: size/XS, cla:yes

#298 Improve tracing document
  components/trace/export.go
  components/trace/generator.go
  diagnostics/exporter_iml/stdout.go
  diagnostics/genetator.go
  diagnostics/tracing.go
  docs/en/start/trace/trace.md
  docs/img/trace/structure.png
  docs/zh/start/trace/trace.md
Labels: cla:yes, size/M

#291 http channel deadconn detection
  components/rpc/invoker/mosn/channel/httpchannel.go
  components/rpc/invoker/mosn/channel/httpchannel_test.go
  pkg/grpc/api.go
Labels: cla:yes, size/L

#226 feat: create reactor-java-sdk refer to dapr-java-sdk
  sdk/java-sdk/pom.xml
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/package-info.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/reactor/AbstractLayottoReactorClient.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/reactor/LayottoReactorClient.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/reactor/LayottoReactorClientBuilder.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/reactor/LayottoReactorClientGrpc.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/BooleanProperty.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/GenericProperty.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/IntegerProperty.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/Properties.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/Property.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/StringProperty.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/CloudEvent.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/SayHelloRequest.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/SayHelloResponse.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/TryLockRequest.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/TryLockResponse.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/UnlockRequest.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/UnlockResponse.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/exceptions/LayottoError.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/exceptions/LayottoException.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/serializer/DefaultObjectSerializer.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/serializer/LayottoObjectSerializer.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/serializer/ObjectSerializer.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/utils/GrpcWrapper.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/utils/NetworkUtils.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/value/Headers.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/value/LayottoApiProtocol.java
  sdk/java-sdk/src/main/java/spec/sdk/reactor/v1/domain/core/invocation/HttpExtension.java
Labels: cla:yes, size/XXL, First-time contributor

#281 docs: add explanation for `operationType` field in proto comments
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/S

#314 fix: remove unused `replicas` field
  components/lock/redis/standalone_redis_lock.go
Labels: bug, size/XS, cla:yes

#284 implement distributied lock with redis cluster
  cmd/layotto/main.go
  components/go.sum
  components/lock/redis/cluster_redis_lock.go
  components/lock/redis/cluster_redis_lock_test.go
  components/pkg/utils/redis.go
  configs/config_lock_redis_cluster.json
  demo/lock/redis/redis_cluster/client_cluster_lock.go
  docs/zh/component_specs/lock/redis.md
  go.mod
  go.sum
Labels: cla:yes, size/XXL, First-time contributor

#313 Refact file interface
  cmd/layotto/main.go
  components/file/alicloud/oss/oss.go
  components/file/alicloud/oss/oss_test.go
  components/file/aws/oss/oss.go
  components/file/errors.go
  components/file/file.go
  components/file/local/file.go
  components/file/local/file_test.go
  components/file/minio/oss/oss.go
  components/file/s3/alicloud/oss.go
  components/file/s3/alicloud/oss_test.go
  components/file/s3/aws/oss.go
  components/file/s3/aws/oss_test.go
  components/file/s3/minio/oss.go
  components/file/s3/minio/oss_test.go
  components/file/s3/util.go
  components/file/s3/util_test.go
  components/file/types.go
  components/go.mod
  components/go.sum
  configs/config_file.json
  demo/file/client.go
  demo/go.mod
  demo/go.sum
  go.mod
  go.sum
  pkg/grpc/api.go
  pkg/grpc/api_errors.go
  pkg/grpc/api_test.go
  pkg/mock/file.go
  pkg/mock/runtime.pb.go
  pkg/runtime/config_test.go
  pkg/runtime/runtime.go
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL

#273 docs: move feature list into table
  README.md
  docs/_sidebar.md
  docs/en/README.md
  docs/en/start/wasm/start.md
  docs/zh/README.md
  docs/zh/_sidebar.md
  docs/zh/start/wasm/start.md
Labels: cla:yes, size/L

#316 improve: Fixed int64 overflow problems on JavaScript
  Makefile
  configs/config_integration_redis_etcd.json
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/L, First-time contributor

#318 add bucket name as args for demo
  demo/file/client.go
Labels: cla:yes, size/S

#319 topic event request add metadata field
  sdk/java-sdk/sdk/src/main/java/io/mosn/layotto/v1/grpc/PubsubConverter.java
  sdk/java-sdk/sdk/src/main/java/spec/proto/runtime/v1/AppCallbackProto.java
  spec/proto/runtime/v1/appcallback.proto
Labels: cla:yes, size/L, First-time contributor

#321 Fix/on topic add metadata
  docs/en/sdk_reference/java/start.md
  docs/zh/sdk_reference/java/start.md
  sdk/java-sdk/README-zh.md
  sdk/java-sdk/README.md
Labels: bug, cla:yes, size/S

#326 doc(java-sdk): add more description in java sdk doc
  sdk/java-sdk/README-zh.md
  sdk/java-sdk/README.md
Labels: cla:yes, size/M

#327 feat: in-memory state store components
  cmd/layotto/main.go
  configs/config_in_memory.json
  demo/state/common/client.go
  docs/en/start/wasm/start.md
  docs/img/wasm/img.png
  docs/img/wasm/img_1.png
  docs/zh/_sidebar.md
  docs/zh/start/wasm/start.md
  pkg/mock/components/state/in_memory_state.go
Labels: cla:yes, size/L

#330 chore(java-sdk): make `getStubManager()` deprecated
  sdk/java-sdk/sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
  sdk/java-sdk/sdk/src/main/java/io/mosn/layotto/v1/grpc/GrpcRuntimeClient.java
Labels: cla:yes, size/S

#329 feat: in-memory pubsub component
  cmd/layotto/main.go
  configs/config_in_memory.json
  demo/pubsub/in-memory/in-memory.go
Labels: cla:yes, size/M

#332 chore: modify in-mem state component name and add demos
  cmd/layotto/main.go
  configs/config_in_memory.json
  demo/pubsub/common/client/publish_client.go
  demo/pubsub/common/server/subscribe_server.go
Labels: cla:yes, size/L

#334 chore(java-sdk): release 1.0.0 sdk
  sdk/java-sdk/README-zh.md
  sdk/java-sdk/README.md
  sdk/java-sdk/examples/pom.xml
  sdk/java-sdk/pom.xml
  sdk/java-sdk/sdk/pom.xml
Labels: cla:yes, size/S

#336 chore(java-sdk): compile example modules into source jar
  sdk/java-sdk/README-zh.md
  sdk/java-sdk/README.md
  sdk/java-sdk/examples/pom.xml
  sdk/java-sdk/examples/src/test/java/io/mosn/layotto/examples/helloworld/Hello.java
  sdk/java-sdk/examples/src/test/java/io/mosn/layotto/examples/pubsub/publisher/Publisher.java
  sdk/java-sdk/examples/src/test/java/io/mosn/layotto/examples/pubsub/subscriber/Subscriber.java
  sdk/java-sdk/examples/src/test/java/io/mosn/layotto/examples/pubsub/subscriber/impl/EventListener.java
  sdk/java-sdk/examples/src/test/java/io/mosn/layotto/examples/pubsub/subscriber/impl/RawSubscriber.java
  sdk/java-sdk/examples/src/test/java/io/mosn/layotto/examples/state/RedisCRUD.java
Labels: cla:yes, size/M

#140 consul lock
  cmd/layotto/main.go
  components/go.mod
  components/go.sum
  components/lock/consul/consul_lock.go
  components/lock/consul/consul_lock_test.go
  components/pkg/utils/consul.go
  components/pkg/utils/consul_mock.go
  configs/config_lock_consul.json
  demo/lock/consul/client.go
  docs/_sidebar.md
  docs/en/component_specs/lock/consul.md
  docs/zh/_sidebar.md
  docs/zh/component_specs/lock/consul.md
Labels: cla:yes, size/XL

#337 doc: Create a start-from-zero guide to become a new contributor
  docs/zh/_sidebar.md
  docs/zh/development/start-from-zero.md
Labels: cla:yes, size/M

#344 Update start-apollo.md
  docs/zh/start/configuration/start-apollo.md
Labels: size/XS, cla:yes
