Repository mosn/layotto, pull requests merged in 2021-08, with the labels that each got.

#163 grpc design docs
  docs/img/actuator/networkfilter-grpc.jpg
  docs/img/actuator/networkfilter.jpg
  docs/zh/_sidebar.md
  docs/zh/design/actuator/grpc-design-doc.md
Labels: First-time contributor, cla:yes, size/L

#152 sequencer redis
  cmd/layotto/main.go
  components/sequencer/redis/standalone_redis_sequencer.go
  components/sequencer/redis/standalone_redis_sequencer_test.go
  components/sequencer/store.go
  configs/config_sequencer_redis.json
  demo/sequencer/redis/client.go
  docs/_sidebar.md
  docs/en/component_specs/sequencer/redis.md
  docs/zh/_sidebar.md
  docs/zh/component_specs/sequencer/redis.md
Labels: cla:yes, size/L

#169 add unittest for runtime and grpc
  go.sum
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/mock/components/invoker/invoker.go
  pkg/mock/components/lock/lock.go
  pkg/mock/components/pubsub/pubsub.go
  pkg/mock/components/sequencer/sequencer.go
  pkg/mock/components/state/state.go
  pkg/mock/runtime/appcallback/appcallback.go
  pkg/runtime/runtime_test.go
Labels: cla:yes, size/XXL

#168 feat: wasm module hot reload
  go.mod
  go.sum
  pkg/wasm/factory.go
  pkg/wasm/watcher.go
Labels: cla:yes, size/L, First-time contributor

#174 add description for wasm in readme
  README.md
  docs/en/README.md
  docs/zh/README.md
Labels: cla:yes, size/S

#181 improve description for lock design (again)
  docs/en/design/lock/lock-api-design.md
Labels: size/XS, cla:yes

#186 fix incorrect md syntax
  docs/zh/design/lock/lock-api-design.md
Labels: bug, size/XS, cla:yes, First-time contributor

#153 simple java client
  sdk/java-sdk/README.md
  sdk/java-sdk/pom.xml
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/SayHelloRequest.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/SayHelloResponse.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/TryLockRequest.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/TryLockResponse.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/UnlockRequest.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/UnlockResponse.java
  sdk/java-sdk/src/main/java/spec/proto/runtime/v1/AppCallbackGrpc.java
  sdk/java-sdk/src/main/java/spec/proto/runtime/v1/AppCallbackProto.java
  sdk/java-sdk/src/main/java/spec/proto/runtime/v1/RuntimeGrpc.java
  sdk/java-sdk/src/main/java/spec/proto/runtime/v1/RuntimeProto.java
  spec/proto/runtime/v1/appcallback.proto
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL

#190 Add RPC API docs
  docs/en/api_reference/rpc/reference.md
  docs/zh/api_reference/rpc/reference.md
Labels: cla:yes

#195 Add data for hello
  pkg/grpc/api.go
  spec/proto/runtime/v1/appcallback.pb.go
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL
