Repository mosn/layotto, pull requests merged in 2021-07, with the labels that each got.

#100 Distributed Lock api
  README-ZH.md
  README.md
  cmd/layotto/main.go
  components/configstores/apollo/indicator.go
  components/go.mod
  components/go.sum
  components/lock/lock_store.go
  components/lock/redis/standalone_redis_lock.go
  components/lock/redis/standalone_redis_lock_test.go
  components/lock/types.go
  components/pkg/actuators/actutors.go
  configs/config_lock_redis.json
  demo/go.mod
  demo/go.sum
  demo/lock/redis/client.go
  docs/en/design/lock/lock-api-design.md
  docs/en/start/lock/start.md
  docs/zh/design/lock/lock-api-design.md
  docs/zh/start/lock/start.md
  img/lock/img.png
  pkg/actuator/health/endpoint.go
  pkg/actuator/health/indicator.go
  pkg/converter/lock.go
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/integrate/actuator/runtime_indicator.go
  pkg/messages/api_errors.go
  pkg/runtime/config.go
  pkg/runtime/lock/factory.go
  pkg/runtime/lock/factory_test.go
  pkg/runtime/lock/lock_config.go
  pkg/runtime/lock/lock_config_test.go
  pkg/runtime/lock/registry.go
  pkg/runtime/lock/registry_test.go
  pkg/runtime/options.go
  pkg/runtime/runtime.go
  sdk/go-sdk/client/client.go
  sdk/go-sdk/client/lock.go
  spec/proto/runtime/v1/appcallback.pb.go
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL

#109 Submit the first version of Proto to generate the Java-SDK file
  sdk/java-sdk/README.md
  sdk/java-sdk/pom.xml
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/AppCallback.java
  sdk/java-sdk/src/main/java/io/mosn/layotto/v1/Runtime.java
Labels: First-time contributor, cla:yes, size/XXL

#110 improve the document for proto compiling
  spec/proto/runtime/v1/README.md
Labels: cla:yes, size/S

#102 add codecov badge
  README-ZH.md
  README.md
Labels: cla:yes, size/XS

#115 add unit tests for rpc related code
  components/go.mod
  components/go.sum
  components/rpc/callback/dubbo_json_rpc_test.go
  components/rpc/invoker/mosn/mosninvoker_test.go
  components/rpc/invoker/mosn/transport_protocol/bolt_test.go
  components/rpc/invoker/mosn/transport_protocol/dubbo.go
  components/rpc/invoker/mosn/transport_protocol/dubbo_test.go
  components/rpc/registry_test.go
  components/rpc/types_test.go
Labels: First-time contributor, cla:yes, size/XL

#117 Add ut for converter and actuator
  CONTRIBUTING_ZH.md
  README-ZH.md
  components/configstores/apollo/configstore_test.go
  components/configstores/apollo/indicator.go
  components/pkg/actuators/actutors.go
  docs/zh/development/developing-component.md
  img/development/component/img_10.png
  img/development/component/img_11.png
  img/development/component/img_8.png
  img/development/component/img_9.png
  img/development/component/mock.png
  pkg/actuator/health/endpoint_test.go
  pkg/actuator/health/indicator.go
  pkg/common/strings_test.go
  pkg/converter/lock_test.go
  pkg/converter/state_test.go
  pkg/integrate/actuator/runtime_indicator.go
  pkg/integrate/actuator/runtime_indicator_test.go
Labels: cla:yes, size/L

#119 return error when panic
  components/rpc/invoker/mosn/mosninvoker.go
  components/rpc/invoker/mosn/mosninvoker_test.go
Labels: cla:yes, question, size/S

#123 replace website url
  README.md
  docs/en/README.md
  docs/zh/README.md
  docs/zh/development/contributing-doc.md
  docs/zh/start/state/start.md
Labels: cla:yes, size/M

#125 Try to fix go import problem
  docs/components
  docs/demo
  docs/index.html
  docs/sdk/go-sdk
  docs/spec
Labels: bug, cla:yes, size/S

#126 upgrade dep
  go.mod
  sdk/go-sdk/go.mod
  sdk/go-sdk/go.sum
Labels: cla:yes, size/XS

#131 remove redundent description in README
  docs/en/README.md
Labels: First-time contributor, cla:yes, size/XS

#128 Add etcd lock
  cmd/layotto/main.go
  components/go.mod
  components/go.sum
  components/lock/etcd/etcd_lock.go
  components/lock/etcd/etcd_lock_test.go
  configs/config_lock_etcd.json
  demo/go.mod
  demo/go.sum
  demo/lock/etcd/client.go
  docs/en/component_specs/lock/etcd.md
  docs/zh/component_specs/lock/etcd.md
  go.mod
  go.sum
Labels: First-time contributor, cla:yes, size/XXL

#121 add assemblyscript wasm demo
  demo/wasm/code/assemblyscript/asconfig.json
  demo/wasm/code/assemblyscript/assembly/index.ts
  demo/wasm/code/assemblyscript/assembly/tsconfig.json
  demo/wasm/code/assemblyscript/index.js
  demo/wasm/code/assemblyscript/package-lock.json
  demo/wasm/code/assemblyscript/package.json
  demo/wasm/config.json
  docs/en/start/wasm/start.md
  docs/zh/start/wasm/start.md
Labels: cla:yes, size/L

#133 add etcd configuration implements
  cmd/layotto/main.go
  components/configstores/etcdv3/etcdv3.go
  components/configstores/etcdv3/etcdv3_test.go
  components/go.mod
  components/go.sum
  docs/_sidebar.md
  docs/en/component_specs/configuration/etcd.md
  docs/zh/_sidebar.md
  docs/zh/component_specs/configuration/etcd.md
  docs/zh/component_specs/lock/etcd.md
  go.sum
Labels: cla:yes, size/XL

#134 fix configuration API ut error
  components/configstores/configstore.go
  go.mod
  go.sum
  pkg/grpc/api.go
  pkg/grpc/api_test.go
Labels: bug, cla:yes, size/M

#111 Zookeeper lock
  cmd/layotto/main.go
  components/go.mod
  components/go.sum
  components/lock/zookeeper/zookeeper_lock.go
  components/lock/zookeeper/zookeeper_lock_mock.go
  components/lock/zookeeper/zookeeper_lock_test.go
  configs/config_lock_zookeeper.json
  demo/lock/zookeeper/client.go
  docs/_sidebar.md
  docs/en/component_specs/lock/zookeeper.md
  docs/zh/_sidebar.md
  docs/zh/component_specs/lock/zookeeper.md
  go.sum
Labels: First-time contributor, cla:yes, size/XL

#135 Add more docs
  components/configstores/apollo/configstore.go
  components/configstores/apollo/repository.go
  docs/_sidebar.md
  docs/en/api_reference/actuator/actuator.md
  docs/en/component_specs/configuration/apollo.md
  docs/en/component_specs/lock/etcd.md
  docs/en/component_specs/pubsub/others.md
  docs/en/component_specs/state/others.md
  docs/en/sdk_reference/go/start.md
  docs/en/sdk_reference/java/start.md
  docs/en/start/configuration/start-apollo.md
  docs/en/start/configuration/start.md
  docs/en/start/lock/start.md
  docs/en/start/network_filter/tcpcopy.md
  docs/en/start/pubsub/start.md
  docs/en/start/state/start.md
  docs/img/configuration/apollo/arch.png
  docs/img/configuration/apollo/img.png
  docs/zh/_sidebar.md
  docs/zh/api_reference/actuator/actuator.md
  docs/zh/component_specs/configuration/apollo.md
  docs/zh/component_specs/lock/etcd.md
  docs/zh/component_specs/lock/zookeeper.md
  docs/zh/component_specs/pubsub/others.md
  docs/zh/component_specs/state/others.md
  docs/zh/development/contributing-doc.md
  docs/zh/sdk_reference/go/start.md
  docs/zh/sdk_reference/java/start.md
  docs/zh/start/configuration/start-apollo.md
  docs/zh/start/configuration/start.md
  docs/zh/start/network_filter/tcpcopy.md
  docs/zh/start/pubsub/start.md
  docs/zh/start/state/start.md
Labels: cla:yes, size/XL

#137 Integrate with Istio
  README.md
  docs/_sidebar.md
  docs/en/README.md
  docs/en/start/istio/start.md
  docs/zh/README.md
  docs/zh/_sidebar.md
  docs/zh/start/istio/start.md
  go.sum
Labels: cla:yes, size/L

#142 add introduction blog.md
  docs/zh/blog/mosn-subproject-layotto-opening-a-new-chapter-in-service-grid-application-runtime/index.md
Labels: cla:yes

#141 Add configuration sidebar
  docs/_sidebar.md
  docs/en/component_specs/overview.md
  docs/en/configuration/overview.md
  docs/zh/README.md
  docs/zh/_sidebar.md
  docs/zh/component_specs/overview.md
  docs/zh/configuration/overview.md
Labels: cla:yes, size/S

#144 change the configuration item `keyPrefix` into `keyPrefixPath` in etcd lock
  components/lock/etcd/etcd_lock.go
  components/lock/etcd/etcd_lock_test.go
  configs/config_lock_etcd.json
  docs/_sidebar.md
  docs/en/component_specs/lock/common.md
  docs/en/component_specs/lock/etcd.md
  docs/zh/_sidebar.md
  docs/zh/component_specs/lock/common.md
  docs/zh/component_specs/lock/etcd.md
Labels: cla:yes, size/M

#124 use standard grpc error codes
  components/rpc/invoker/mosn/channel/channel.go
  components/rpc/invoker/mosn/channel/connpool.go
  components/rpc/invoker/mosn/channel/httpchannel.go
  components/rpc/invoker/mosn/channel/xchannel.go
  components/rpc/invoker/mosn/transport_protocol/bolt.go
  components/rpc/invoker/mosn/transport_protocol/dubbo.go
Labels: cla:yes, size/L

#145 Add api reference for State API
  docs/_sidebar.md
  docs/en/api_reference/actuator/actuator.md
  docs/en/api_reference/state/reference.md
  docs/en/component_specs/lock/common.md
  docs/en/component_specs/state/common.md
  docs/en/start/state/start.md
  docs/zh/_sidebar.md
  docs/zh/api_reference/actuator/actuator.md
  docs/zh/api_reference/state/reference.md
  docs/zh/component_specs/lock/common.md
  docs/zh/component_specs/state/common.md
  docs/zh/start/state/start.md
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes

#147 Add Sequencer api
  README.md
  cmd/layotto/main.go
  components/sequencer/const.go
  components/sequencer/etcd/store.go
  components/sequencer/etcd/store_test.go
  components/sequencer/store.go
  components/sequencer/types.go
  configs/config_sequencer_etcd.json
  demo/go.mod
  demo/sequencer/common/client.go
  docs/_sidebar.md
  docs/en/README.md
  docs/en/component_specs/sequencer/common.md
  docs/en/component_specs/sequencer/etcd.md
  docs/en/start/configuration/overview.md
  docs/en/start/configuration/start-apollo.md
  docs/en/start/configuration/start.md
  docs/img/development/api/img.png
  docs/img/development/api/img_1.png
  docs/img/development/api/img_2.png
  docs/img/development/api/img_3.png
  docs/img/development/api/img_4.png
  docs/img/sequencer/design/leaf_max_id.png
  docs/img/sequencer/etcd/img.png
  docs/zh/README.md
  docs/zh/_sidebar.md
  docs/zh/api_reference/sequencer/reference.md
  docs/zh/component_specs/sequencer/common.md
  docs/zh/component_specs/sequencer/etcd.md
  docs/zh/design/sequencer/design.md
  docs/zh/development/developing-api.md
  docs/zh/development/developing-component.md
  docs/zh/start/configuration/overview.md
  docs/zh/start/configuration/start-apollo.md
  docs/zh/start/configuration/start.md
  docs/zh/start/lock/start.md
  docs/zh/start/sequencer/start.md
  go.mod
  pkg/converter/sequencer.go
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/messages/api_errors.go
  pkg/runtime/config.go
  pkg/runtime/options.go
  pkg/runtime/runtime.go
  pkg/runtime/sequencer/cache.go
  pkg/runtime/sequencer/factory.go
  pkg/runtime/sequencer/factory_test.go
  pkg/runtime/sequencer/registry.go
  pkg/runtime/sequencer/registry_test.go
  sdk/go-sdk/client/client.go
  sdk/go-sdk/client/sequencer.go
  sdk/go-sdk/go.mod
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL

#151 Add english version of sequencer API docs
  docs/_sidebar.md
  docs/en/api_reference/sequencer/reference.md
  docs/en/start/configuration/start-apollo.md
  docs/en/start/lock/start.md
  docs/en/start/pubsub/start.md
  docs/en/start/sequencer/start.md
  docs/en/start/state/start.md
  docs/zh/_sidebar.md
  docs/zh/start/configuration/start-apollo.md
  docs/zh/start/lock/start.md
  docs/zh/start/pubsub/start.md
  docs/zh/start/sequencer/start.md
  docs/zh/start/state/start.md
Labels: cla:yes, size/L

#155 add cleanup in connpool
  components/pkg/common/error.go
  components/rpc/invoker/mosn/channel/channel.go
  components/rpc/invoker/mosn/channel/connpool.go
  components/rpc/invoker/mosn/channel/connpool_test.go
  components/rpc/invoker/mosn/channel/httpchannel.go
  components/rpc/invoker/mosn/channel/xchannel.go
  components/rpc/invoker/mosn/channel/xchannel_test.go
  components/rpc/invoker/mosn/transport_protocol/bolt.go
  components/rpc/invoker/mosn/transport_protocol/bolt_test.go
  components/rpc/invoker/mosn/transport_protocol/dubbo.go
  components/rpc/invoker/mosn/transport_protocol/dubbo_test.go
  go.mod
  pkg/grpc/api.go
Labels: cla:yes, size/L

#160 add more features for go sdk
  sdk/go-sdk/client/client.go
  sdk/go-sdk/client/client_test.go
  sdk/go-sdk/client/invoke.go
  sdk/go-sdk/client/invoke_test.go
  sdk/go-sdk/client/pubsub.go
  sdk/go-sdk/client/pubsub_test.go
Labels: cla:yes, size/XL

#157 Isolation and code reuse of components
  components/lock/etcd/etcd_lock.go
  components/lock/redis/standalone_redis_lock.go
  components/pkg/utils/etcd.go
  components/pkg/utils/redis.go
  components/sequencer/const.go
  components/sequencer/etcd/store.go
  components/sequencer/types.go
  docs/_sidebar.md
  docs/en/api_reference/lock/reference.md
  docs/en/api_reference/pubsub/reference.md
  docs/en/api_reference/state/reference.md
  docs/en/component_specs/lock/common.md
  docs/en/component_specs/pubsub/common.md
  docs/en/component_specs/sequencer/common.md
  docs/en/configuration/overview.md
  docs/img/configuration/layotto/img.png
  docs/zh/_sidebar.md
  docs/zh/api_reference/lock/reference.md
  docs/zh/api_reference/pubsub/reference.md
  docs/zh/api_reference/state/reference.md
  docs/zh/component_specs/lock/common.md
  docs/zh/component_specs/pubsub/common.md
  docs/zh/component_specs/sequencer/common.md
  docs/zh/configuration/overview.md
  pkg/grpc/api.go
  pkg/runtime/lock/lock_config.go
  pkg/runtime/lock/lock_config_test.go
  pkg/runtime/sequencer/utils.go
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL

#161 add feature list doc
  README.md
  docs/en/README.md
  docs/zh/README.md
Labels: cla:yes, size/L

#162 Revert "add feature list doc"
  README.md
  docs/en/README.md
  docs/zh/README.md
Labels: cla:yes, size/L
