Repository mosn/layotto, pull requests merged in 2022-09, with the labels that each got.

#774 chore: modify code structure to make it easier to generate code.
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  cmd/layotto_without_xds/main.go
  pkg/grpc/context_generated.go
  pkg/grpc/grpc_api.go
  pkg/runtime/component_generated.go
  pkg/runtime/config.go
  pkg/runtime/config_generated.go
  pkg/runtime/context_generated.go
  pkg/runtime/options.go
  pkg/runtime/options_generated.go
  pkg/runtime/runtime.go
  sdk/go-sdk/client/client.go
  sdk/go-sdk/client/client_generated.go
  spec/proto/extension/v1/email/email.proto
Labels: cla:yes, size/L

#779 feat: code generator
  docs/_sidebar.md
  docs/en/api_reference/how_to_generate_api_doc.md
  docs/zh/_sidebar.md
  docs/zh/api_reference/how_to_generate_api_doc.md
  etc/script/generate-code.sh
  make/proto.mk
  pkg/grpc/errors.go
  pkg/grpc/lifecycle/grpc_api.go
  spec/proto/extension/v1/email/email.proto
  spec/proto/extension/v1/phone/phone.proto
  spec/proto/extension/v1/s3/oss.proto
  spec/proto/runtime/v1/lifecycle_grpc.pb.go
Labels: cla:yes, size/L

#787 fix: example errors & ci errors
  configs/config.json
  configs/config_apollo.json
  configs/config_consul.json
  configs/config_file.json
  configs/config_file_qiniu_oss.json
  configs/config_file_tencentcloud_oss.json
  configs/config_mongo.json
  configs/config_redis.json
  configs/config_standalone.json
  configs/config_trace_jaeger.json
  configs/config_trace_skywalking.json
  configs/config_trace_zipkin.json
  configs/config_zookeeper.json
  configs/runtime_config.json
  demo/flowcontrol/client.go
  demo/lifecycle/common/client.go
  deploy/k8s/sidecar/default_quickstart_counter.yaml
  deploy/k8s/standalone/default_configmap.yaml
  deploy/k8s/standalone/default_quickstart.yaml
  docker/layotto-etcd/etcd_config.json
  docker/layotto-minio/config_minio.json
  docker/layotto-redis/config_redis.json
  docs/en/start/email/start.md
  docs/en/start/lifecycle/start.md
  docs/en/start/oss/start.md
  docs/en/start/phone/start.md
  docs/en/start/pubsub/start.md
  docs/en/start/sequencer/start.md
  docs/en/start/state/start.md
  docs/template/quickstart.tmpl
  docs/template/quickstart_zh.tmpl
  docs/zh/design/actuator/grpc-design-doc.md
  docs/zh/start/email/start.md
  docs/zh/start/lifecycle/start.md
  docs/zh/start/phone/start.md
  docs/zh/start/pubsub/start.md
  docs/zh/start/sequencer/start.md
  docs/zh/start/state/start.md
  sdk/go-sdk/test/runtime/redis_integrate_test.go
Labels: bug, cla:yes, size/L

#789 fix: Incorrect conversion between integer types
  components/rpc/invoker/mosn/mosninvoker.go
Labels: bug, size/XS, cla:yes

#788 chore: set deadlink validation to schedule, move out of PRs
  .github/workflows/dead-link-checker.yaml
  .github/workflows/stale.yml
Labels: size/XS, cla:yes

#785 refactor: infra and cmds
  .github/workflows/dead-link-checker.yaml
  .github/workflows/layotto-ci.yml
  .github/workflows/layotto-release.yml
  .github/workflows/quickstart-checker.yml
  Makefile
  docs/en/api_reference/how_to_generate_api_doc.md
  docs/en/development/commands.md
  docs/zh/api_reference/how_to_generate_api_doc.md
  docs/zh/development/commands.md
  make/ci.mk
  make/common.mk
  make/deploy.mk
  make/golang.mk
  make/help.mk
  make/image.mk
  make/proto.mk
  make/wasm.mk
Labels: cla:yes, size/XL

#783 docs: lock demo
  docs/en/start/lock/start.md
  docs/zh/start/lock/start.md
Labels: cla:yes, size/L

#798 fix(docs): deadlink in sidebar
  docs/zh/_sidebar.md
Labels: bug, size/XS, cla:yes

#802 chore: upgrade components-contrib
  go.mod
  go.sum
Labels: size/XS, cla:yes

#803 feat: use copier to convert structs
  go.mod
  go.sum
  pkg/grpc/delay_queue/server.go
  pkg/grpc/email/server.go
  pkg/grpc/phone/server.go
Labels: cla:yes, size/L

#805 chore: remove linters which is deprecated
  .golangci.yml
Labels: size/XS, cla:yes
