Repository mosn/layotto, pull requests merged in 2022-11, with the labels that each got.

#834 chore: remove go.test.verify
  make/golang.mk
Labels: size/XS, cla:yes

#835 fix: add xds v3 default config
  configs/config.json
  configs/config_apollo.json
  configs/config_consul.json
  configs/config_file.json
  configs/config_file_qiniu_oss.json
  configs/config_file_tencentcloud_oss.json
  configs/config_integrate_test.json
  configs/config_mongo.json
  configs/config_oss.json
  configs/config_redis.json
  configs/config_ref_example.json
  configs/config_snowflake.json
  configs/config_standalone.json
  configs/config_trace_jaeger.json
  configs/config_trace_skywalking.json
  configs/config_trace_zipkin.json
  configs/config_zookeeper.json
  configs/runtime_config.json
  demo/faas/config.json
  demo/rpc/dubbo_json_rpc/example.json
  demo/rpc/http/example.json
Labels: bug, cla:yes, size/XXL

#837 chore: add templates for sdk good first issues
  .github/ISSUE_TEMPLATE/good-first-issue-component.md
  .github/ISSUE_TEMPLATE/good-first-issue-java-sdk.md
  .github/ISSUE_TEMPLATE/good-first-issue-js-sdk.md
Labels: cla:yes, size/M

#839 fix: error when running WASM quickstart
  docs/en/start/wasm/start.md
  docs/zh/start/wasm/start.md
  pkg/wasm/dispatch.go
  pkg/wasm/factory.go
  pkg/wasm/factory_test.go
Labels: bug, question, cla:yes, size/M

#841 chore: improve issue templates && generator templates
  .github/ISSUE_TEMPLATE/good-first-issue-component.md
  .github/ISSUE_TEMPLATE/good-first-issue-go-demo.md
  .github/ISSUE_TEMPLATE/good-first-issue-java-demo.md
  docs/api/v1/cryption.html
  docs/api/v1/delay_queue.html
  docs/api/v1/email.html
  docs/api/v1/phone.html
  docs/api/v1/runtime.html
  docs/api/v1/s3.html
  docs/api/v1/sms.html
  docs/en/start/cryption/start.md
  docs/en/start/delay_queue/start.md
  docs/en/start/email/start.md
  docs/en/start/lock/start.md
  docs/en/start/phone/start.md
  docs/en/start/sms/start.md
  docs/template/api_ref_html.tmpl
  docs/template/quickstart.tmpl
  docs/template/quickstart_zh.tmpl
  docs/zh/start/cryption/start.md
  docs/zh/start/delay_queue/start.md
  docs/zh/start/email/start.md
  docs/zh/start/phone/start.md
  docs/zh/start/sms/start.md
  spec/proto/extension/v1/delay_queue/delay_queue.proto
  spec/proto/extension/v1/phone/phone.proto
Labels: cla:yes, size/XXL

#844 fix: update document for faas start
  docs/en/start/faas/start.md
  docs/zh/start/faas/start.md
Labels: bug, cla:yes
