Repository mosn/layotto, pull requests merged in 2022-04, with the labels that each got.

#454 chore: upgrade mosn to v0.27.0
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  go.mod
  go.sum
Labels: cla:yes, size/M

#446 doc: Automatically test quickstart document for state API
  demo/state/redis/client.go
  docs/en/start/state/start.md
  docs/zh/_sidebar.md
  docs/zh/development/test-quickstart.md
  docs/zh/start/state/start.md
Labels: cla:yes, size/L

#451 ci: check dead link and test quickstart
  .dlc.json
  .github/workflows/dead-link-checker.yaml
  .github/workflows/github-actions.yml
  .github/workflows/test-quickstart.yml
  Makefile
  components/configstores/apollo/configstore.go
  docs/_coverpage.md
  docs/en/design/configuration/configuration-api-with-apollo.md
  docs/en/development/contributing-doc.md
  docs/en/development/explanation-for-github-workflow.md
  docs/en/start/configuration/start-apollo.md
  docs/en/start/state/start.md
  docs/en/start/trace/trace.md
  docs/img/development/workflow/img_2.png
  docs/zh/community/governance.md
  docs/zh/design/configuration/configuration-api-with-apollo.md
  docs/zh/development/contributing-doc.md
  docs/zh/development/explanation-for-github-workflow.md
  docs/zh/start/configuration/start-apollo.md
  etc/script/check-dead-link.sh
  etc/script/test-quickstart.sh
Labels: cla:yes, size/L

#459 fix: dubbo demo fails (#458)
  demo/rpc/dubbo_json_rpc/dubbo_json_client/client.go
  docs/en/start/rpc/dubbo_json_rpc.md
  docs/zh/start/rpc/dubbo_json_rpc.md
Labels: bug, cla:yes, size/M

#464 fix: replace official demo with local minio
  configs/config_file.json
  demo/file/client.go
  docs/zh/start/file/minio.md
Labels: bug, cla:yes, size/M

#477 chore: upgrade dep
  .github/pr-title-checker-config.json
  go.mod
  go.sum
Labels: cla:yes, size/S

#481 chore: update version to latest tag
  VERSION
Labels: size/XS, cla:yes

#487 feature: add state anno
  pkg/grpc/dapr/dapr_api_state.go
  pkg/grpc/default_api/api_state.go
  pkg/runtime/state/compatibility.go
  pkg/runtime/state/factory.go
  pkg/runtime/state/registry.go
Labels: cla:yes, size/M, First-time contributor

#479 feature: add actuator comments
  pkg/actuator/actuator.go
  pkg/actuator/actuator_test.go
  pkg/actuator/endpoint.go
  pkg/actuator/health/endpoint.go
  pkg/actuator/health/indicator.go
  pkg/actuator/info/contributor.go
  pkg/actuator/info/endpoint.go
Labels: cla:yes, size/S, First-time contributor

#492 fix: binary file prints wrong information
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
Labels: bug, cla:yes, size/S

#493 fix: don't register apollo actuator when no apollo component configurated
  components/configstores/apollo/configstore.go
  components/pkg/actuators/actutors_test.go
  components/pkg/actuators/indicator.go
  components/pkg/actuators/indicator_test.go
  components/sequencer/in-memory/in_memory_sequencer.go
Labels: bug, cla:yes, size/L

#486 feat: upgrade assemblyscript faas demo(#256)
  demo/faas/code/assemblyscript/README.md
  demo/faas/code/assemblyscript/asconfig.json
  demo/faas/code/assemblyscript/assembly/client.ts
  demo/faas/code/assemblyscript/assembly/index.ts
  demo/faas/code/assemblyscript/assembly/proxy.ts
  demo/faas/code/assemblyscript/assembly/server.ts
  demo/faas/code/assemblyscript/build/.gitignore
  demo/faas/code/assemblyscript/index.js
  demo/faas/code/assemblyscript/package-lock.json
  demo/faas/code/assemblyscript/package.json
Labels: cla:yes, size/L, First-time contributor

#475 feature: Upgrade the wasm demo developed by rust(#255)
  demo/faas/code/rust/.gitignore
  demo/faas/code/rust/.rustfmt.toml
  demo/faas/code/rust/Cargo.lock
  demo/faas/code/rust/Cargo.toml
  demo/faas/code/rust/README.md
  demo/faas/code/rust/client/Cargo.toml
  demo/faas/code/rust/client/src/lib.rs
  demo/faas/code/rust/lib.rs
  demo/faas/code/rust/proxy-wasm/Cargo.toml
  demo/faas/code/rust/proxy-wasm/src/dispatcher.rs
  demo/faas/code/rust/proxy-wasm/src/lib.rs
  demo/faas/code/rust/proxy-wasm/src/traits.rs
  demo/faas/code/rust/proxy-wasm/src/types.rs
  demo/faas/code/rust/server/Cargo.toml
  demo/faas/code/rust/server/src/lib.rs
Labels: cla:yes, size/XL, First-time contributor

#495 feat: add secret client for go sdk
  sdk/go-sdk/client/client.go
  sdk/go-sdk/client/client_test.go
  sdk/go-sdk/client/secret.go
  sdk/go-sdk/client/secret_test.go
Labels: cla:yes, size/M

#482 chore: add more badges to layotto and refactor layouts
  README.md
  docs/en/README.md
  docs/zh/README.md
Labels: cla:yes, size/M

#506 doc: improve document contribution guide
  docs/zh/development/contributing-doc.md
Labels: cla:yes, size/M

#494 doc: layotto rpc code analysis
  docs/zh/_sidebar.md
  docs/zh/blog/code/flowcontrol/flowcontrol_code_analyze.md
  docs/zh/blog/code/layotto-rpc/index.md
Labels: cla:yes, size/XL

#474 doc: translate 'explanation-for-github-workflow' into chinese
  docs/zh/development/explanation-for-github-workflow.md
Labels: cla:yes, size/M
