Repository mosn/layotto, pull requests merged in 2022-06, with the labels that each got.

#619 docs:solve the problem of URL inaccessibility
  docs/index.html
  docs/js/docsify-plugin-flexible-alerts.min.js
  docs/js/docsify-sidebar-collapse.min.js
  docs/js/docsify-tabs.min.js
  docs/js/index.js
  docs/js/progress.js
  docs/js/time-updater.min.js
  docs/zh/README.md
Labels: cla:yes, size/L, First-time contributor

#621 docs: update image url to fix the inaccessibility
  docs/en/README.md
  docs/zh/README.md
  docs/zh/start/state/start.md
Labels: bug, cla:yes, size/S

#590 feat: add jaeger
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  configs/config_trace_jaeger.json
  diagnostics/jaeger/grpc_tracer.go
  diagnostics/jaeger/jaeger-docker-compose.yaml
  docs/zh/_sidebar.md
  docs/zh/start/trace/jaeger.md
  etc/script/test-quickstart.sh
  go.mod
  go.sum
Labels: cla:yes, size/L, community meeting topic

#616 docs: remove “last update time of this doc”
  docs/index.html
Labels: cla:yes, size/S

#629 fix: configuration API returns wrong app_id
  pkg/grpc/default_api/api_configuration.go
Labels: bug, size/XS, cla:yes, First-time contributor

#632 chore: Use docker-compose to run quickstart
  configs/config.json
  diagnostics/jaeger/grpc_tracer.go
  diagnostics/skywalking/grpc_tracer.go
  docker/layotto-redis/config_redis.json
  docker/layotto-redis/docker-compose.yml
  docs/_sidebar.md
  docs/en/development/contributing-doc.md
  docs/en/start/lock/start.md
  docs/en/start/pubsub/start.md
  docs/en/start/secret/start.md
  docs/en/start/state/start.md
  docs/zh/_sidebar.md
  docs/zh/development/contributing-doc.md
  docs/zh/operation/README.md
  docs/zh/start/lock/start.md
  docs/zh/start/pubsub/start.md
  docs/zh/start/secret/start.md
  docs/zh/start/sequencer/start.md
  docs/zh/start/state/start.md
Labels: cla:yes, size/XL

#633 feat: translate test-quickstart
  docs/_sidebar.md
  docs/en/development/test-quickstart.md
Labels: cla:yes, size/L

#526 feat: replace pr title validator
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-checker.yml
Labels: cla:yes, size/M, community meeting topic

#638 ci: upgrade title checker
  .github/workflows/pr-title-checker.yml
Labels: size/XS, cla:yes

#639 chore: fix the CI
  .github/workflows/pr-title-checker.yml
Labels: bug, size/XS, cla:yes

#644 fix: jaeger tracer nil pointer
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  etc/script/test-quickstart.sh
Labels: bug, cla:yes, size/S

#637 ci: compile proto files into code and doc
  Makefile
  docker/proto/Dockerfile
  docs/_sidebar.md
  docs/en/api_reference/how_to_generate_api_doc.md
  docs/zh/_sidebar.md
  docs/zh/api_reference/how_to_generate_api_doc.md
  make/proto.mk
  spec/proto/runtime/v1/README.md
  spec/proto/runtime/v1/appcallback.pb.go
  spec/proto/runtime/v1/appcallback_grpc.pb.go
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime_grpc.pb.go
Labels: cla:yes, size/XXL

#648 chore: Use docker-compose to start minIO and layotto
  docker/layotto-minio/config_minio.json
  docker/layotto-minio/docker-compose.yml
  docs/zh/start/file/minio.md
Labels: cla:yes, size/L, First-time contributor

#650 chore: demo should panic when errors occur
  demo/bindings/main.go
  demo/configuration/common/client.go
  demo/file/client.go
  demo/lock/consul/client.go
  demo/lock/etcd/client.go
  demo/lock/in-memory/client.go
  demo/lock/mongo/client.go
  demo/lock/redis/client.go
  demo/lock/redis/redis_cluster/client_cluster_lock.go
  demo/lock/zookeeper/client.go
  docs/en/component_specs/lock/etcd.md
  docs/en/component_specs/lock/zookeeper.md
  docs/zh/component_specs/lock/etcd.md
  docs/zh/component_specs/lock/zookeeper.md
Labels: question, cla:yes, size/XL

#656 docs(en): add en operation doc
  docs/_sidebar.md
  docs/en/operation/README.md
Labels: cla:yes, size/M, First-time contributor

#657 chore: use docker-compose to start etcd and layotto #635
  docker/layotto-etcd/docker-compose.yml
  docker/layotto-etcd/etcd_config.json
  docs/en/start/configuration/start.md
  docs/en/start/sequencer/start.md
  docs/zh/start/configuration/start.md
  docs/zh/start/sequencer/start.md
Labels: cla:yes, size/L, First-time contributor

#658 fix: Unit tests fail in component package
  components/file/s3/qiniu/qiniu_oss_client_test.go
  components/file/s3/qiniu/qiniu_oss_test.go
  components/go.mod
  components/go.sum
  go.sum
Labels: bug, cla:yes, size/S, First-time contributor

#641 fix: configuration API returns wrong `store_name`
  components/configstores/apollo/change_listener.go
  components/configstores/apollo/change_listener_test.go
  components/configstores/apollo/configstore.go
  components/configstores/apollo/configstore_test.go
  components/configstores/apollo/const.go
  components/configstores/apollo/repository.go
  components/configstores/etcdv3/etcdv3.go
  components/configstores/etcdv3/etcdv3_test.go
  pkg/runtime/runtime.go
Labels: bug, cla:yes, size/M

#642 feat: add zipkin
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  configs/config_trace_zipkin.json
  diagnostics/zipkin/grpc_tracer.go
  diagnostics/zipkin/zipkin-docker-compose.yaml
  docs/zh/_sidebar.md
  docs/zh/start/trace/zipkin.md
  etc/script/test-quickstart.sh
  go.mod
  go.sum
Labels: cla:yes, size/L

#662 fix: jaeger code error
  configs/config_trace_jaeger.json
  diagnostics/jaeger/grpc_tracer.go
  docs/zh/start/trace/jaeger.md
Labels: bug, cla:yes, size/M

#663 refactor: replace current apollo sdk with the official one
  components/configstores/apollo/change_listener.go
  components/configstores/apollo/change_listener_test.go
  components/configstores/apollo/repository.go
  components/go.mod
  components/go.sum
  go.sum
Labels: cla:yes, size/S

#667 docs: automatically add space between chinese and english
  docs/index.html
  docs/js/pangu.min.js
Labels: size/XS, cla:yes

#668 docs: translate and update configuration-api-with-apollo
  docs/en/design/configuration/configuration-api-with-apollo.md
  docs/zh/README.md
  docs/zh/design/configuration/configuration-api-with-apollo.md
Labels: cla:yes, size/L

#673 chore: upgrade mosn dependency
  components/go.mod
  components/go.sum
  components/rpc/invoker/mosn/channel/channel.go
  go.mod
  go.sum
Labels: cla:yes, size/L, First-time contributor

#676 chore: upgrade mosn dependency
  components/go.mod
  components/go.sum
  components/rpc/invoker/mosn/channel/channel.go
  go.mod
  go.sum
Labels: cla:yes, size/L

#677 docs: update community doc
  .gitignore
  docs/zh/community/meeting.md
  docs/zh/community/promote.md
Labels: cla:yes, size/S

#681 docs: Translate the api-plugin quickstart into Chinese
  docs/zh/start/api_plugin/helloworld.md
Labels: cla:yes, size/M, First-time contributor

#678 ci: make error message in "🌈 Go Style Check" more readable
  make/common.mk
  make/golang.mk
Labels: size/XS, cla:yes

#683 docs: run state and sequencer quickstart with java sdk
  docs/en/start/sequencer/start.md
  docs/en/start/state/start.md
  docs/zh/start/README.md
  docs/zh/start/sequencer/start.md
  docs/zh/start/state/start.md
Labels: cla:yes, size/L, dont-check-PRs-with-this-label

#685 feat: specify callback ip in config.json
  demo/pubsub/client/publish_client.go
  demo/pubsub/server/subscribe_server.go
  docker/layotto-redis/config_redis.json
  docs/en/start/pubsub/start.md
  docs/zh/start/pubsub/start.md
  pkg/runtime/config.go
  pkg/runtime/runtime.go
Labels: cla:yes, size/L
