Repository mosn/layotto, pull requests merged in 2022-05, with the labels that each got.

#516 fix(ci): push amd64 image should remove suffix
  make/image.mk
Labels: bug, size/XS, cla:yes

#518 docs: fix sidebars for new pages
  docs/_sidebar.md
  docs/zh/_sidebar.md
Labels: bug, size/XS, cla:yes

#515 docs: improve doc site
  docs/_navbar.md
  docs/css/font.css
  docs/css/vue.css
  docs/index.html
  docs/zh/README.md
  docs/zh/_navbar.md
  docs/zh/_sidebar.md
  docs/zh/community/meeting.md
  docs/zh/start/configuration/start-apollo.md
  docs/zh/video/README.md
Labels: cla:yes, size/L

#517 chore: remove `VERSION` for new pipelines
  VERSION
Labels: size/XS, cla:yes

#499 docs: add tcpdump blog.
  docs/zh/_sidebar.md
  docs/zh/blog/tcpcopy_code_analyze.md
Labels: cla:yes, size/L, First-time contributor

#524 fix: Publish subscription caused by metadata does not fill in caused …
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
Labels: bug, cla:yes, size/S, First-time contributor

#537 fix: FaaS quickstart fails
  docs/zh/start/faas/start.md
Labels: bug, size/XS, cla:yes

#523 fix:aws oss
  components/file/s3/aws/oss.go
  components/file/s3/aws/oss_test.go
Labels: bug, cla:yes, size/S, First-time contributor

#522 fix: add version to build flags
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  make/golang.mk
Labels: bug, cla:yes, size/S

#542 fix: makefile commands in docs
  docs/en/start/faas/start.md
Labels: bug, size/XS, cla:yes

#543 fix: error format when debugging logs
  pkg/filter/network/tcpcopy/strategy/fuse.go
Labels: bug, question, size/XS, cla:yes

#538 docs: analysis start process
  docs/zh/_sidebar.md
  docs/zh/blog/code/start_process/start_process.md
Labels: cla:yes, size/L

#536 feat: optimize codes and reopen lint test ci
  .github/workflows/layotto-ci.yml
  .github/workflows/layotto-release.yml
  .golangci.yml
  components/configstores/apollo/configstore.go
  components/configstores/apollo/configstore_test.go
  components/configstores/apollo/errors.go
  components/configstores/apollo/repository.go
  pkg/actuator/actuator_test.go
  pkg/actuator/health/endpoint.go
  pkg/actuator/health/indicator.go
  pkg/actuator/info/endpoint.go
  pkg/common/log.go
  pkg/filter/network/tcpcopy/portrait_data.go
  pkg/filter/network/tcpcopy/strategy/switch.go
  pkg/filter/stream/actuator/http/dispatch_filter.go
  pkg/grpc/dapr/dapr_api.go
  pkg/grpc/default_api/api.go
  pkg/grpc/default_api/api_configuration.go
  pkg/grpc/default_api/api_file.go
  pkg/grpc/default_api/api_file_test.go
  pkg/grpc/default_api/api_pubsub.go
  pkg/grpc/default_api/api_pubsub_test.go
  pkg/grpc/default_api/api_sequencer.go
  pkg/grpc/grpc.go
  pkg/integrate/actuator/runtime_indicator.go
  pkg/runtime/bindings/registry.go
  pkg/runtime/config_test.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/runtime/sequencer/cache.go
  pkg/wasm/dispatch.go
  test/wasm/wasm_test.go
Labels: cla:yes, size/L, dont-check-PRs-with-this-label

#546 ci: reopen unit test checks and fix fatal
  .github/workflows/layotto-ci.yml
  .github/workflows/layotto-release.yml
  go.mod
  go.sum
  make/golang.mk
Labels: bug, cla:yes, size/S

#456 ci: test all the quickstart documents
  .github/workflows/quickstart-checker.yml
  demo/configuration/common/client.go
  demo/configuration/etcd/etcd.go
  demo/lock/redis/client.go
  demo/state/common/client.go
  demo/state/redis/client.go
  docs/en/component_specs/lock/etcd.md
  docs/en/component_specs/lock/zookeeper.md
  docs/en/component_specs/sequencer/etcd.md
  docs/en/component_specs/sequencer/in-memory.md
  docs/en/component_specs/sequencer/redis.md
  docs/en/component_specs/sequencer/zookeeper.md
  docs/en/start/actuator/start.md
  docs/en/start/api_plugin/helloworld.md
  docs/en/start/configuration/start-apollo.md
  docs/en/start/configuration/start.md
  docs/en/start/lock/start.md
  docs/en/start/pubsub/start.md
  docs/en/start/rpc/dubbo_json_rpc.md
  docs/en/start/rpc/helloworld.md
  docs/en/start/sequencer/start.md
  docs/en/start/state/start.md
  docs/en/start/trace/trace.md
  docs/en/start/wasm/start.md
  docs/zh/component_specs/lock/etcd.md
  docs/zh/component_specs/lock/in-memory.md
  docs/zh/component_specs/lock/zookeeper.md
  docs/zh/component_specs/sequencer/etcd.md
  docs/zh/component_specs/sequencer/in-memory.md
  docs/zh/component_specs/sequencer/redis.md
  docs/zh/component_specs/sequencer/zookeeper.md
  docs/zh/design/api_plugin/design.md
  docs/zh/development/test-quickstart.md
  docs/zh/start/actuator/start.md
  docs/zh/start/api_plugin/helloworld.md
  docs/zh/start/configuration/start-apollo.md
  docs/zh/start/configuration/start.md
  docs/zh/start/file/minio.md
  docs/zh/start/lock/start.md
  docs/zh/start/pubsub/start.md
  docs/zh/start/rpc/dubbo_json_rpc.md
  docs/zh/start/rpc/helloworld.md
  docs/zh/start/sequencer/start.md
  docs/zh/start/state/start.md
  docs/zh/start/trace/skywalking.md
  docs/zh/start/trace/trace.md
  docs/zh/start/wasm/start.md
  etc/script/download_etcd.sh
  etc/script/test-quickstart.sh
  make/ci.mk
Labels: cla:yes, size/XXL, ci

#551 sync: add code of conduct to meet standards
  CODE_OF_CONDUCT.md
Labels: cla:yes, size/L

#552 docs: improve quickstart contribution guide
  docs/zh/development/test-quickstart.md
  etc/script/test-quickstart.sh
Labels: cla:yes, size/S

#553 docs: add video demonstration for layotto workflow
  docs/zh/development/github-workflows.md
Labels: cla:yes, size/M

#560 docs(design): fix a typo
  docs/zh/design/file/file-design.md
Labels: bug, cla:yes, size/S, First-time contributor

#555 docs: improve quickstart contribution guide
  docs/zh/development/test-quickstart.md
Labels: cla:yes, size/M

#566 ci: automatically upload binary files when releasing new version
  .github/workflows/layotto-release.yml
Labels: question, cla:yes, size/M, First-time contributor

#480 feature: Add prometheus demo
  demo/prometheus/prometheus-docker-compose.yaml
  demo/prometheus/prometheus.yml
  docs/_sidebar.md
  docs/en/start/trace/prometheus.md
  docs/en/start/trace/skywalking.md
  docs/zh/_sidebar.md
  docs/zh/start/trace/prometheus.md
  etc/script/test-quickstart.sh
Labels: cla:yes, size/L

#562 ci: fix CI issues and improve make script
  .gitignore
  Makefile
  etc/script/test-quickstart.sh
  make/golang.mk
Labels: cla:yes, size/M

#525 docs: add secret demo and doc
  configs/config_secret_file.json
  configs/secret/config_secret_local_file.json
  demo/secret/common/client.go
  docs/_sidebar.md
  docs/en/component_specs/secret/common.md
  docs/en/start/secret/start.md
  docs/zh/_sidebar.md
  docs/zh/component_specs/secret/common.md
  docs/zh/start/secret/start.md
  etc/script/test-quickstart.sh
  pkg/runtime/config.go
Labels: cla:yes, size/L

#570 docs: add contributors graph
  README.md
  docs/en/README.md
  docs/zh/README.md
Labels: cla:yes, size/S

#568 docs: improve contribution guide
  docs/zh/_sidebar.md
  docs/zh/development/CONTRIBUTING.md
  docs/zh/development/commands.md
  docs/zh/development/release-guide.md
  docs/zh/development/test-quickstart.md
Labels: cla:yes, size/M

#572 chore(make): `make license` to add licnese headers for all code files.
  Makefile
  docs/en/development/commands.md
  docs/zh/development/commands.md
Labels: cla:yes, size/S

#578 docs(secret): `secretStores` -> `secret_store`
  docs/en/component_specs/secret/common.md
  docs/zh/component_specs/secret/common.md
Labels: size/XS, cla:yes

#582 fix: add `secretstores.Metadata`
  demo/configuration/common/README.md
  demo/secret/common/README.md
  demo/secret/common/client.go
  demo/state/common/README.md
  pkg/runtime/config.go
  pkg/runtime/secretstores/metadata.go
Labels: bug, cla:yes, size/M

#583 fix: goimports failed in make all
  make/golang.mk
Labels: bug, cla:yes, size/S

#581 docs :translate the zh to en
  docs/en/development/github-workflows.md
Labels: cla:yes, size/L, First-time contributor

#600 feature: optimized sequencer api demo
  demo/sequencer/common/README.md
  demo/sequencer/common/client.go
  demo/sequencer/in-memory/client.go
  demo/sequencer/mongo/client.go
  demo/sequencer/redis/client.go
  demo/sequencer/zookeeper/client.go
Labels: cla:yes, size/L

#602 ci: fix license script
  Makefile
  make/ci.mk
  pkg/wasm/abi.go
  sdk/go-sdk/client/secret.go
Labels: bug, cla:yes, size/M

#604 fix: fix legacy issues of #549
  components/custom/registry.go
  pkg/runtime/runtime.go
  sdk/go-sdk/client/client_test.go
Labels: bug, cla:yes, size/M

#601 ci: linter check submodules
  .github/workflows/layotto-ci.yml
  .github/workflows/layotto-release.yml
  .golangci.yml
  components/configstores/apollo/configstore.go
  components/configstores/apollo/configstore_test.go
  components/configstores/apollo/repository.go
  components/configstores/etcdv3/etcdv3.go
  components/configstores/etcdv3/etcdv3_test.go
  components/file/hdfs/hdfs.go
  components/file/hdfs/hdfs_test.go
  components/file/local/file.go
  components/file/local/file_test.go
  components/file/s3/alicloud/oss.go
  components/file/s3/alicloud/oss_test.go
  components/file/s3/aws/oss.go
  components/file/s3/aws/oss_test.go
  components/file/s3/minio/oss.go
  components/file/s3/qiniu/qiniu_oss_test.go
  components/file/s3/tencentcloud/oss.go
  components/file/s3/tencentcloud/oss_test.go
  components/lock/consul/consul_lock.go
  components/lock/consul/consul_lock_test.go
  components/lock/etcd/etcd_lock.go
  components/lock/mongo/mongo_lock.go
  components/lock/mongo/mongo_lock_test.go
  components/lock/redis/cluster_redis_lock.go
  components/lock/redis/cluster_redis_lock_test.go
  components/lock/zookeeper/zookeeper_lock_test.go
  components/pkg/common/error.go
  components/pkg/utils/etcd.go
  components/pkg/utils/mongo.go
  components/pkg/utils/redis.go
  components/rpc/invoker/mosn/channel/httpchannel.go
  components/rpc/invoker/mosn/channel/xchannel_test.go
  components/rpc/invoker/mosn/mosninvoker.go
  components/sequencer/etcd/store.go
  components/sequencer/etcd/store_test.go
  components/trace/utils_test.go
  demo/configuration/common/client.go
  demo/faas/code/golang/go.mod
  demo/faas/code/golang/go.sum
  demo/file/client.go
  demo/file/qiniu/client.go
  demo/file/stressmem.go
  demo/file/tencentcloud/client.go
  demo/go.mod
  demo/go.sum
  demo/lock/common/client.go
  demo/lock/zookeeper/client.go
  demo/pubsub/in-memory/in-memory.go
  docs/en/start/lock/start.md
  docs/zh/start/lock/start.md
  etc/script/resolve-modules.sh
  make/golang.mk
  sdk/go-sdk/client/client.go
  sdk/go-sdk/client/secret.go
  sdk/go-sdk/client/state.go
  sdk/go-sdk/client/state_test.go
Labels: cla:yes, size/XL

#594 feature: Optimized pubsub api demo
  demo/pubsub/README.md
  demo/pubsub/client/publish_client.go
  demo/pubsub/common/client/publish_client.go
  demo/pubsub/common/server/subscribe_server.go
  demo/pubsub/redis/client/publish_client.go
  demo/pubsub/server/subscribe_server.go
  docs/en/start/pubsub/start.md
  docs/zh/start/pubsub/start.md
Labels: cla:yes, size/L, First-time contributor

#575 docs: webassembly code analysis
  docs/zh/_sidebar.md
  docs/zh/blog/code/webassembly/index.md
Labels: cla:yes, size/XL
