Repository mosn/layotto, pull requests merged in 2022-01, with the labels that each got.

#276 feat:add hdfs support
  .github/workflows/github-actions.yml
  components/file/hdfs/hdfs.go
  components/file/hdfs/hdfs_test.go
  components/go.mod
  components/go.sum
  go.mod
  go.sum
Labels: cla:yes, size/XL, First-time contributor

#378 doc: Fix wrong link
  docs/_sidebar.md
  docs/en/start/rpc/helloworld.md
  docs/zh/_sidebar.md
  docs/zh/start/rpc/helloworld.md
Labels: bug, cla:yes, size/S

#377 feature: support dapr state api
  go.mod
  go.sum
  pkg/converter/state.go
  pkg/converter/state_test.go
  pkg/grpc/dapr/dapr_api_state.go
  pkg/grpc/dapr/dapr_api_unimplement.go
  pkg/grpc/default_api/api.go
  pkg/grpc/default_api/api_state.go
  pkg/messages/api_errors.go
  pkg/runtime/state/compatibility.go
Labels: cla:yes, size/XXL

#380 add metric config for layotto
  cmd/layotto/main.go
  configs/runtime_config.json
  docs/_sidebar.md
  docs/en/start/trace/trace.md
  docs/img/trace/metric.png
  docs/zh/_sidebar.md
  docs/zh/start/trace/trace.md
Labels: cla:yes, size/L
