Repository mosn/layotto, pull requests merged in 2022-12, with the labels that each got.

#847 docs: improve generator docs
  docs/en/start/api_plugin/generate.md
  docs/zh/start/api_plugin/generate.md
Labels: cla:yes, size/S

#849 feat: upgrade golang version to 1.18
  .github/workflows/layotto-ci.yml
  .github/workflows/layotto-release.yml
  components/go.mod
  components/go.sum
  docker/app/faas/Dockerfile
  docker/app/integrate/Dockerfile
  docker/proto/Dockerfile
  go.mod
  go.sum
  spec/go.mod
Labels: cla:yes, size/XL

#850 feat: Upgrade golang 1.18
  .github/workflows/quickstart-checker.yml
  etc/script/test-quickstart.sh
Labels: cla:yes, size/S

#848 feat: update mosn version v1.3.0
  cmd/layotto/main.go
  components/go.mod
  components/go.sum
  components/trace/utils.go
  components/trace/utils_test.go
  diagnostics/genetator.go
  docs/en/start/trace/trace.md
  docs/zh/start/trace/trace.md
  go.mod
  go.sum
  pkg/filter/network/tcpcopy/portrait_data.go
  pkg/filter/stream/common/http/dispatch_filter.go
  pkg/wasm/abi.go
  pkg/wasm/filter.go
  pkg/wasm/runtime/wasmtime/debug.go
  pkg/wasm/runtime/wasmtime/debug_test.go
  pkg/wasm/runtime/wasmtime/function.go
  pkg/wasm/runtime/wasmtime/instance.go
  pkg/wasm/runtime/wasmtime/instance_test.go
  pkg/wasm/runtime/wasmtime/module.go
  pkg/wasm/runtime/wasmtime/testdata/data.wasm
  pkg/wasm/runtime/wasmtime/types.go
  pkg/wasm/runtime/wasmtime/vm.go
Labels: cla:yes, size/XXL
