Repository mosn/layotto, pull requests merged in 2022-02, with the labels that each got.

#382 doc: improve metrics doc
  configs/runtime_config.json
  docs/zh/start/trace/trace.md
Labels: cla:yes, size/L

#343 feat: ADD SECRET API
  cmd/layotto/main.go
  components/go.mod
  components/go.sum
  go.mod
  go.sum
  pkg/grpc/dapr/dapr_api.go
  pkg/grpc/dapr/dapr_api_secret.go
  pkg/grpc/dapr/dapr_api_test.go
  pkg/grpc/dapr/dapr_api_unimplement.go
  pkg/grpc/default_api/api.go
  pkg/grpc/default_api/api_test.go
  pkg/grpc/grpc_api.go
  pkg/messages/api_errors.go
  pkg/mock/components/secret/secret.go
  pkg/runtime/config.go
  pkg/runtime/config_test.go
  pkg/runtime/options.go
  pkg/runtime/runtime.go
  pkg/runtime/secretstores/factory.go
  pkg/runtime/secretstores/registry.go
  pkg/runtime/secretstores/registry_test.go
  pkg/wasm/imports_test.go
  spec/go.sum
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL

#385 docs: add cncf landscape logo in README
  README.md
  docs/en/README.md
  docs/zh/README.md
Labels: cla:yes, size/S

#387 doc: add a release guide
  docs/img/development/release/img.png
  docs/img/development/release/img_1.png
  docs/zh/_sidebar.md
  docs/zh/development/release-guide.md
Labels: cla:yes, size/M

#388 feat: don't compile the actuator module if users don't need it
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  components/configstores/apollo/indicator.go
  components/go.sum
  components/pkg/actuators/actutors.go
  pkg/integrate/actuator/grpc.go
  pkg/runtime/runtime.go
Labels: cla:yes, size/L

#391 fix: correct wrong symbols
  docs/zh/start/istio/start.md
Labels: bug, size/XS, cla:yes

#390 update *.pb.go
  spec/proto/runtime/v1/appcallback.pb.go
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XXL

#395 fix: make ut deterministic
  components/configstores/apollo/change_listener.go
  components/configstores/apollo/change_listener_test.go
  components/go.sum
  components/rpc/invoker/mosn/channel/xchannel.go
  components/rpc/invoker/mosn/channel/xchannel_test.go
Labels: bug, cla:yes, size/S

#394 feat: add file api impl tencent cloud oss
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  components/file/s3/tencentcloud/oss.go
  components/file/s3/tencentcloud/oss_test.go
  components/go.mod
  components/go.sum
  configs/config_file_tencentcloud_oss.json
  demo/file/tencentcloud/client.go
  docs/img/file/create_tencent_oss_bucket.png
  docs/zh/component_specs/file/tencentcloud_oss.md
  go.sum
Labels: cla:yes, size/XL

#393 doc: modify community promotion rules
  docs/zh/community/governance.md
  docs/zh/community/promote.md
Labels: cla:yes, size/M

#396 feat: add some file api ut and improve codecov
  components/file/hdfs/hdfs_test.go
  components/file/s3/alicloud/oss_test.go
  components/file/s3/aws/oss_test.go
Labels: cla:yes, size/L

#397 docs: add file api tencent cloud oss english doc
  codecov.yml
  docs/en/component_specs/file/tencentcloud_oss.md
Labels: cla:yes, size/M
