Repository mosn/layotto, pull requests merged in 2022-03, with the labels that each got.

#402 feat: improve components mock dir and workflow check
  .licenserc.yaml
  codecov.yml
  components/lock/consul/consul_lock_test.go
  components/lock/zookeeper/zookeeper_lock_test.go
  components/pkg/mock/consul_mock.go
  components/pkg/mock/zookeeper_mock.go
  components/sequencer/zookeeper/zookeeper_sequencer_test.go
Labels: cla:yes, size/M

#400 feat(config.json): schema change
  configs/config_apollo.json
  configs/config_apollo_health.json
  configs/config_apollo_health_mq.json
  configs/config_file.json
  configs/config_integration_redis_etcd.json
  configs/runtime_config.json
  configs/wrong/config_apollo_health.json
  docs/en/component_specs/state/common.md
  docs/en/start/configuration/start.md
  docs/zh/component_specs/file/common.md
  docs/zh/component_specs/state/common.md
  docs/zh/design/actuator/grpc-design-doc.md
  docs/zh/design/file/file-design.md
  docs/zh/start/configuration/start.md
  docs/zh/start/file/minio.md
  pkg/runtime/config.go
  pkg/runtime/config_test.go
  pkg/runtime/state/compatibility.go
  pkg/runtime/state/compatibility_test.go
Labels: cla:yes, size/M

#407 Split mosn layotto
  components/rpc/invoker/mosn/channel/channel.go
  components/rpc/invoker/mosn/channel/httpchannel.go
  components/rpc/invoker/mosn/channel/xchannel.go
Labels: cla:yes, size/S

#409 fix: broken links
  README.md
Labels: bug, size/XS, cla:yes

#401 feat: add file qiniu cloud oss
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  components/file/s3/qiniu/qiniu_oss_client.go
  components/file/s3/qiniu/qiniu_oss_client_test.go
  components/file/s3/qiniu/qiniu_oss_test.go
  components/file/s3/qiniu/quniu_oss.go
  components/go.mod
  components/go.sum
  components/pkg/mock/qiniu_client_mock.go
  configs/config_file_qiniu_oss.json
  demo/file/qiniu/client.go
  docs/en/component_specs/file/qiniu_oss.md
  docs/zh/component_specs/file/qiniu_oss.md
  go.mod
  go.sum
Labels: cla:yes, size/XXL

#398 feat: add in-memory sequencer
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  components/go.mod
  components/sequencer/in-memory/in_memory_sequencer.go
  components/sequencer/in-memory/in_memory_sequencer_test.go
  configs/config_in_memory.json
  demo/sequencer/in-memory/client.go
  docs/zh/component_specs/sequencer/in-memory.md
Labels: cla:yes, size/L

#399 feat: add in-memory lock
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  components/lock/in-memory/in_memory_lock.go
  components/lock/in-memory/in_memory_lock_test.go
  configs/config_in_memory.json
  demo/lock/in-memory/client.go
  docs/zh/component_specs/lock/in-memory.md
Labels: cla:yes, size/L

#421 fix: compile warning on mac os 12
  go.mod
  go.sum
Labels: bug, cla:yes, size/S

#423 doc: delete `config_apollo_health_mq.json`
  configs/config_apollo_health_mq.json
  docs/en/component_specs/pubsub/common.md
  docs/en/component_specs/pubsub/redis.md
  docs/en/start/pubsub/start.md
  docs/zh/component_specs/pubsub/common.md
  docs/zh/component_specs/pubsub/redis.md
  docs/zh/start/pubsub/start.md
Labels: cla:yes, size/L

#432 doc: improve readme
  README.md
  docs/en/README.md
  docs/zh/README.md
Labels: cla:yes, size/L

#429 doc: improve document for api plugin
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  docs/zh/_sidebar.md
  docs/zh/design/api_plugin/design.md
  pkg/grpc/grpc_api.go
Labels: cla:yes, size/L

#433 doc: fix markdown errors in api-plugin doc
  docs/img/api_plugin/img.png
  docs/zh/design/api_plugin/design.md
Labels: bug, cla:yes, size/M

#441 fix(demo):fix etcd demos
  demo/lock/etcd/client.go
  docs/en/start/configuration/start.md
  docs/zh/start/configuration/start.md
Labels: bug, cla:yes, size/L

#435 doc: add operation guide
  docs/_sidebar.md
  docs/en/configuration/overview.md
  docs/zh/_sidebar.md
  docs/zh/building_blocks/README.md
  docs/zh/component_specs/overview.md
  docs/zh/configuration/README.md
  docs/zh/configuration/overview.md
  docs/zh/operation/README.md
  docs/zh/start/README.md
Labels: cla:yes, size/L

#440 ci: Pr title check
  .github/pr-title-checker-config.json
  .github/workflows/pr_title_check.yml
  docs/en/development/explanation-for-github-workflow.md
  docs/zh/development/explanation-for-github-workflow.md
Labels: cla:yes, size/M

#404 feat: add skywalking trace
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  codecov.yml
  components/trace/span.go
  configs/config_trace_skywalking.json
  diagnostics/grpc/grpc_request.go
  diagnostics/grpc_tracing.go
  diagnostics/protocol/protocol.go
  diagnostics/skywalking/grpc_tracer.go
  diagnostics/skywalking/skywalking-docker-compose.yaml
  diagnostics/tracing.go
  docs/img/trace/sky.png
  docs/zh/README.md
  docs/zh/_sidebar.md
  docs/zh/start/trace/skywalking.md
  go.mod
  go.sum
Labels: cla:yes, size/L

#408 chore: optimize dockerfiles and makefiles
  .github/workflows/github-actions.yml
  Makefile
  build/contrib/builder/binary/Dockerfile
Labels: cla:yes, size/M

#410 ci: add auto build and release workflow
  .github/workflows/publish.yml
Labels: cla:yes, size/M

#445 doc: fix minio & tcpcopy quickstart
  configs/config_file.json
  demo/file/client.go
  docs/zh/start/file/minio.md
  docs/zh/start/network_filter/tcpcopy.md
Labels: bug, cla:yes, size/M

#428 fix: add debug log for apollo component
  components/configstores/apollo/configstore.go
  components/configstores/apollo/configstore_test.go
  docs/en/design/configuration/configuration-api-with-apollo.md
  docs/en/start/actuator/start.md
  docs/en/start/configuration/start-apollo.md
  docs/zh/design/configuration/configuration-api-with-apollo.md
  docs/zh/start/actuator/start.md
  docs/zh/start/configuration/start-apollo.md
Labels: cla:yes, size/L
