Repository mosn/layotto, pull requests merged in 2022-07, with the labels that each got.

#695 fix: hello component
  components/hello/registry.go
Labels: bug, size/XS, cla:yes

#696 fix: deadlinks cause ci failed
  docs/en/start/faas/start.md
  docs/zh/start/faas/start.md
Labels: bug, size/XS, cla:yes

#697 feat: deploy Layotto with istio 1.10
  cmd/layotto/cmd.go
  cmd/layotto/main.go
  docs/en/start/rpc/dubbo_json_rpc.md
  docs/en/start/wasm/start.md
  docs/zh/start/rpc/dubbo_json_rpc.md
  docs/zh/start/wasm/start.md
  go.mod
  go.sum
Labels: cla:yes, size/L

#698 chore: use `start --config` parameters in some demos
  docs/zh/start/file/minio.md
  docs/zh/start/secret/start.md
Labels: size/XS, cla:yes

#701 fix: ut unstable of zk lock
  components/lock/zookeeper/zookeeper_lock.go
  components/lock/zookeeper/zookeeper_lock_test.go
Labels: bug, cla:yes, size/M

#711 docs: add `secret_ref.md` into sidebar
  configs/config_ref_example.json
  docs/_sidebar.md
  docs/en/start/secret/secret_ref.md
  docs/zh/_sidebar.md
  docs/zh/start/secret/secret_ref.md
Labels: cla:yes, size/M

#719 docs: add guide for local development & add label spec
  docs/zh/_sidebar.md
  docs/zh/development/label-spec.md
  docs/zh/operation/local.md
Labels: cla:yes, size/M

#718 docs: fix stale contributor guide
  docs/zh/development/start-from-zero.md
Labels: bug, size/XS, cla:yes

#703 docs: fix stale description for community roles
  docs/img/community/img.png
  docs/zh/community/governance.md
  docs/zh/community/people.md
Labels: bug, cla:yes, size/S

#720 docs: add docs for istio integration
  README.md
  docs/_sidebar.md
  docs/en/README.md
  docs/en/operation/README.md
  docs/en/start/istio/README.md
  docs/en/start/istio/start.md
  docs/en/start/lab.md
  docs/zh/README.md
  docs/zh/_sidebar.md
  docs/zh/operation/README.md
  docs/zh/start/README.md
  docs/zh/start/istio/README.md
  docs/zh/start/istio/start.md
  docs/zh/start/lab.md
Labels: cla:yes, size/L, dont-check-PRs-with-this-label

#721 docs: add local connect to remote layotto sidecar guide
  docs/zh/operation/README.md
  docs/zh/operation/local.md
Labels: cla:yes, size/S

#605 feat: implement sequencer api with mysql
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  components/go.mod
  components/go.sum
  components/pkg/utils/mysql.go
  components/sequencer/mysql/mysql.go
  components/sequencer/mysql/mysql_test.go
  docs/_sidebar.md
  docs/en/component_specs/sequencer/mysql.md
  docs/zh/_sidebar.md
  docs/zh/component_specs/sequencer/mysql.md
Labels: cla:yes, size/XL, component

#465 feat: Add support for Dapr pubsub API
  pkg/grpc/dapr/dapr_api.go
  pkg/grpc/dapr/dapr_api_pubsub.go
  pkg/grpc/dapr/dapr_api_pubsub_test.go
  pkg/grpc/dapr/dapr_api_unimplement.go
  pkg/grpc/default_api/api_pubsub.go
  pkg/mock/runtime/appcallback/daprAppcallback.go
Labels: cla:yes, size/XL, community meeting topic, api

#725 chore: improve dapr pubsub api
  pkg/grpc/dapr/dapr_api.go
  pkg/grpc/dapr/dapr_api_pubsub.go
  pkg/mock/runtime/appcallback/dapr_appcallback.go
Labels: cla:yes, size/M

#728 docs: add demo deploy k8s standalone yaml.
  demo/deploy/k8s/standalone/default_configmap.yaml
  demo/deploy/k8s/standalone/default_deployment.yaml
  demo/deploy/k8s/standalone/default_quickstart.yaml
Labels: cla:yes, size/L

#733 ci: add `proto` file comments linter
  .github/workflows/proto-linter.yml
  buf.yaml
  make/proto.mk
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/L

#731 feat: add cmds to deploy layotto
  Makefile
  deploy/k8s/standalone/default_configmap.yaml
  deploy/k8s/standalone/default_deployment.yaml
  deploy/k8s/standalone/default_quickstart.yaml
  make/common.mk
  make/deploy.mk
Labels: cla:yes, size/M

#735 ci: rename CI jobs to keep naming style consistent
  .github/workflows/markdown-checker.yml
  .github/workflows/proto-checker.yml
  components/rpc/invoker/mosn/channel/channel.go
  demo/rpc/http/example.json
Labels: cla:yes, size/L

#736 docs: update proto file docs
  docs/en/api_reference/comment_spec_of_proto.md
  docs/en/api_reference/runtime_v1.md
  docs/zh/api_reference/comment_spec_of_proto.md
Labels: cla:yes, size/L

#737 ci: deadlink checker ignores https://docs.buf.build/
  .github/dead_link_check_config.json
Labels: size/XS, cla:yes

#740 docs: fix expired QR code
  README.md
  docs/en/README.md
Labels: bug, size/XS, cla:yes

#742 chore: add a demo for deployment on k8s as a sidecar
  deploy/k8s/sidecar/default_quickstart_counter.yaml
  pkg/grpc/extension/s3/s3.go
Labels: cla:yes, size/L

#743 docs: improve dev guide
  docs/zh/operation/local.md
Labels: cla:yes, size/S

#746 chore: some cleanup work for oss api
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  cmd/layotto_without_xds/main.go
  components/file/aws/file.go
  components/file/aws/file_test.go
  components/file/minio/oss.go
  components/file/minio/oss_test.go
  components/oss/oss.go
  configs/config_file.json
  configs/config_file_qiniu_oss.json
  configs/config_file_tencentcloud_oss.json
  docker/layotto-minio/config_minio.json
  docs/_sidebar.md
  docs/en/api_reference/oss_v1.md
  docs/zh/_sidebar.md
  docs/zh/api_reference/README.md
  docs/zh/blog/code/start_process/start_process.md
  docs/zh/component_specs/file/common.md
  docs/zh/design/file/file-design.md
  docs/zh/start/file/minio.md
  make/proto.mk
  pkg/runtime/config_test.go
  spec/proto/runtime/v1/runtime.pb.go
  spec/proto/runtime/v1/runtime_grpc.pb.go
Labels: cla:yes, size/XXL
