Repository mosn/layotto, pull requests merged in 2022-08, with the labels that each got.

#749 docs: add oss quickstart into the sidebar
  docs/zh/_sidebar.md
Labels: cla:yes

#752 fix: GetNextId in ZK component throw zk: node does not exist
  components/sequencer/zookeeper/zookeeper_sequencer.go
Labels: bug, size/XS, cla:yes

#758 fix: move s3 pb to specify directory
  demo/oss/client.go
  pkg/grpc/extension/s3/s3.go
  pkg/grpc/extension/s3/s3_test.go
  pkg/mock/runtime/oss/oss.go
  spec/proto/extension/v1/s3/oss.pb.go
  spec/proto/extension/v1/s3/oss.proto
  spec/proto/extension/v1/s3/oss_grpc.pb.go
Labels: bug, cla:yes, size/XXL

#760 feat: move bookinfo yaml in layotto
  deploy/k8s/bookinfo/bookinfo-gateway.yaml
  deploy/k8s/bookinfo/bookinfo.yaml
  deploy/k8s/bookinfo/destination-rule-all.yaml
  deploy/k8s/bookinfo/virtual-service-all-v1.yaml
Labels: cla:yes, size/XL

#764 chore: auto-generate the pb code and api-reference docs based on the proto files
  Makefile
  docs/_sidebar.md
  docs/api/v1/runtime.html
  docs/api/v1/s3.html
  docs/en/api_reference/README.md
  docs/en/api_reference/how_to_generate_api_doc.md
  docs/zh/api_reference/README.md
  docs/zh/api_reference/how_to_generate_api_doc.md
  etc/script/generate-code.sh
  etc/script/generate-doc.sh
  make/proto.mk
  spec/proto/runtime/v1/html.tmpl
Labels: cla:yes, size/XXL

#729 feat(api): add `email.proto`
  spec/proto/runtime/v1/email.proto
Labels: cla:yes, size/L

#727 feat(api): add `ivr.proto`
  docs/en/design/notify/phone_call.md
  spec/proto/runtime/v1/phone_call.proto
Labels: cla:yes, size/L

#769 feat: doc generator
  docs/_sidebar.md
  docs/api/v1/s3.html
  docs/en/api_reference/how_to_generate_api_doc.md
  docs/en/building_blocks/rpc/reference.md
  docs/en/start/oss/start.md
  docs/template/api_ref_html.tmpl
  docs/template/api_ref_md.tmpl
  docs/template/quickstart.tmpl
  docs/template/quickstart_zh.tmpl
  docs/zh/_sidebar.md
  docs/zh/api_reference/how_to_generate_api_doc.md
  docs/zh/building_blocks/rpc/reference.md
  docs/zh/design/oss/design.md
  docs/zh/start/oss/oss.md
  docs/zh/start/sequencer/start.md
  etc/script/generate-doc.sh
  spec/proto/extension/v1/s3/oss.proto
  spec/proto/runtime/v1/appcallback.proto
  spec/proto/runtime/v1/runtime.proto
Labels: cla:yes, size/XL

#770 chore: upgrade dependency mosn to v1.1.0
  cmd/layotto/cmd.go
  cmd/layotto_multiple_api/cmd.go
  cmd/layotto_without_xds/cmd.go
  components/go.mod
  components/go.sum
  go.mod
  go.sum
Labels: cla:yes, size/M

#771 feat(sdk): OSS go sdk
  sdk/go-sdk/client/client.go
Labels: size/XS, cla:yes

#762 feat: modify component configuration during runtime
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  cmd/layotto_without_xds/main.go
  components/hello/helloworld/helloworld.go
  components/hello/helloworld/helloworld_test.go
  components/pkg/common/dynamic_component.go
  demo/lifecycle/common/client.go
  docs/_sidebar.md
  docs/api/v1/runtime.html
  docs/en/start/lifecycle/start.md
  docs/zh/_sidebar.md
  docs/zh/design/lifecycle/apply_configuration.md
  docs/zh/start/lifecycle/start.md
  etc/script/generate-doc.sh
  etc/script/test-quickstart.sh
  pkg/grpc/grpc_api.go
  pkg/grpc/lifecycle/errors.go
  pkg/grpc/lifecycle/grpc_api.go
  pkg/runtime/lifecycle/const.go
  pkg/runtime/lifecycle/types.go
  pkg/runtime/runtime.go
  spec/proto/extension/v1/email/email.proto
  spec/proto/extension/v1/phone/phone_call.proto
  spec/proto/runtime/v1/lifecycle.pb.go
  spec/proto/runtime/v1/lifecycle.proto
  spec/proto/runtime/v1/lifecycle_grpc.pb.go
Labels: cla:yes, size/XXL
