Repository mosn/layotto, pull requests merged in 2022-10, with the labels that each got.

#804 docs: secret demo
  docs/en/start/secret/start.md
  docs/zh/start/secret/start.md
Labels: cla:yes, size/M, First-time contributor

#806 docs: translate hot_to_generate_api_doc
  docs/zh/api_reference/how_to_generate_api_doc.md
Labels: cla:yes, size/L, First-time contributor

#807 feat: azure-servicebus component for DelayQueue API
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  cmd/layotto_without_xds/main.go
  components/delay_queue/azure/servicebus/servicebus.go
  components/go.mod
  components/go.sum
  go.sum
Labels: cla:yes, size/M

#815 chore: rename `seeflood/protoc-gen-p6` to `layotto/protoc-gen-p6`
  components/delay_queue/interface_generated.go
  components/delay_queue/struct_generated.go
  components/email/interface_generated.go
  components/email/struct_generated.go
  components/email/types_generated.go
  components/phone/interface_generated.go
  components/phone/struct_generated.go
  components/phone/types_generated.go
  docs/en/api_reference/how_to_generate_api_doc.md
  docs/en/start/api_plugin/generate.md
  docs/zh/api_reference/how_to_generate_api_doc.md
  docs/zh/start/api_plugin/generate.md
  etc/script/generate-code.sh
  make/proto.mk
  pkg/grpc/context_generated.go
  pkg/grpc/delay_queue/server.go
  pkg/grpc/email/server.go
  pkg/grpc/phone/server.go
  pkg/runtime/component_generated.go
  pkg/runtime/config_generated.go
  pkg/runtime/context_generated.go
  pkg/runtime/extension_api_generated.go
  pkg/runtime/options_generated.go
  sdk/go-sdk/client/client_generated.go
Labels: cla:yes, size/M

#813 feat: add js document
  docs/en/start/lock/start.md
  docs/zh/start/lock/start.md
Labels: cla:yes, size/M, First-time contributor

#817 fix: Revert "feat: add js document"
  docs/en/start/lock/start.md
  docs/zh/start/lock/start.md
Labels: bug, cla:yes, size/M

#811 feat: return rpc detail error message
  components/rpc/invoker/mosn/mosninvoker.go
  components/rpc/invoker/mosn/transport_protocol/bolt.go
  components/rpc/invoker/mosn/transport_protocol/bolt_test.go
  components/rpc/types.go
  pkg/grpc/dapr/dapr_api.go
Labels: cla:yes, size/M

#795 test: add integrate test
  configs/config_integrate_test.json
  configs/secret/config_test_secret_demo.json
  docker/app/integrate/Dockerfile
  sdk/go-sdk/test/runtime/integrate_test.go
  sdk/go-sdk/test/runtime/integrate_test.sh
  sdk/go-sdk/test/runtime/other_component_integrate_test.go
  sdk/go-sdk/test/runtime/redis_integrate_test.go
  sdk/go-sdk/test/runtime/zkCreateZnode.sh
Labels: cla:yes, size/XL

#767 feat: add sequencer api component with snowflake algorithm
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  cmd/layotto_without_xds/main.go
  components/go.mod
  components/go.sum
  components/sequencer/snowflake/snowflake.go
  components/sequencer/snowflake/snowflake_sequencer.go
  components/sequencer/snowflake/snowflake_sequencer_test.go
  components/sequencer/snowflake/snowflake_test.go
  configs/config_snowflake.json
  docs/_sidebar.md
  docs/en/component_specs/sequencer/snowflake.md
  docs/zh/_sidebar.md
  docs/zh/component_specs/sequencer/snowflake.md
Labels: cla:yes, size/XXL, First-time contributor

#821 feat: add ContentLength for oss Putobject
  components/oss/oss.go
  docs/api/v1/s3.html
  spec/proto/extension/v1/cryption/cryption.pb.go
  spec/proto/extension/v1/cryption/cryption_grpc.pb.go
  spec/proto/extension/v1/delay_queue/delay_queue.pb.go
  spec/proto/extension/v1/delay_queue/delay_queue_grpc.pb.go
  spec/proto/extension/v1/email/email.pb.go
  spec/proto/extension/v1/email/email_grpc.pb.go
  spec/proto/extension/v1/phone/phone.pb.go
  spec/proto/extension/v1/phone/phone_grpc.pb.go
  spec/proto/extension/v1/s3/oss.pb.go
  spec/proto/extension/v1/s3/oss.proto
  spec/proto/extension/v1/sms/sms.pb.go
  spec/proto/extension/v1/sms/sms_grpc.pb.go
  spec/proto/runtime/v1/appcallback.pb.go
  spec/proto/runtime/v1/lifecycle.pb.go
  spec/proto/runtime/v1/runtime.pb.go
Labels: cla:yes, size/XXL

#823 feat(generator): generate less code and doc
  components/rpc/invoker/mosn/channel/httpchannel.go
  docs/zh/blog/code/layotto-rpc/index.md
  docs/zh/design/rpc/rpc设计文档.md
  etc/script/generate-code.sh
  etc/script/generate-doc.sh
  spec/proto/extension/v1/cryption/cryption.pb.go
  spec/proto/extension/v1/cryption/cryption.proto
  spec/proto/extension/v1/cryption/cryption_grpc.pb.go
  spec/proto/extension/v1/delay_queue/delay_queue.pb.go
  spec/proto/extension/v1/delay_queue/delay_queue.proto
  spec/proto/extension/v1/delay_queue/delay_queue_grpc.pb.go
  spec/proto/extension/v1/email/email.pb.go
  spec/proto/extension/v1/email/email.proto
  spec/proto/extension/v1/email/email_grpc.pb.go
  spec/proto/extension/v1/phone/phone.pb.go
  spec/proto/extension/v1/phone/phone.proto
  spec/proto/extension/v1/phone/phone_grpc.pb.go
  spec/proto/extension/v1/s3/oss.pb.go
  spec/proto/extension/v1/sms/sms.pb.go
  spec/proto/extension/v1/sms/sms.proto
  spec/proto/extension/v1/sms/sms_grpc.pb.go
  spec/proto/runtime/v1/appcallback.pb.go
  spec/proto/runtime/v1/lifecycle.pb.go
  spec/proto/runtime/v1/runtime.pb.go
Labels: cla:yes, size/XXL

#825 chore: add an issue template for good first issues
  .github/ISSUE_TEMPLATE/good-first-issue-component.md
Labels: cla:yes, size/M

#831 chore: add issue templates
  .github/ISSUE_TEMPLATE/good-first-issue-component.md
  .github/ISSUE_TEMPLATE/good-first-issue-translate-into-chinese.md
  .github/ISSUE_TEMPLATE/good-first-issue-translate-into-english.md
  .github/ISSUE_TEMPLATE/good-first-issue-ut.md
  components/rpc/invoker/mosn/channel/xchannel.go
Labels: cla:yes, size/M
