Repository mosn/layotto, pull requests merged in 2023-03, with the labels that each got.

#877 ci: add prow bot to manage issues and PRs
  .github/workflows/kube-bot.yaml
Labels: cla:yes, size/L

#866 chore: add comments using chatGPT
  components/go.mod
  demo/bindings/main.go
  demo/file/client.go
  demo/oss/client.go
Labels: cla:yes, size/L, approved, lgtm

#881 chore: clean-up workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/dead-link-checker.yaml
  .github/workflows/kube-bot.yaml
  .github/workflows/layotto-ci.yml
  .github/workflows/layotto-release.yml
  .github/workflows/license-checker.yml
  .github/workflows/markdown-checker.yml
  .github/workflows/pr-title-checker.yml
  .github/workflows/proto-checker.yml
  .github/workflows/quickstart-checker.yml
  .github/workflows/stale.yml
Labels: cla:yes, size/M, approved, lgtm

#868 test: add UT and fix a typo using chatGPT
  components/oss/registry.go
  components/oss/registry_test.go
Labels: bug, cla:yes, size/L, priority/medium, area/test, approved, lgtm

#883 ci: update prow bot
  .github/workflows/kube-bot.yaml
  OWNERS
Labels: cla:yes, size/M, priority/medium, area/ci, area/community, approved, lgtm

#885 chore: enable debug log
  .github/workflows/kube-bot.yaml
Labels: cla:yes, size/S

#886 ci: use schedule prow merge
  .github/workflows/kube-bot.yaml
Labels: size/XS, cla:yes

#887 docs: improve doc to test prow bot
  docs/en/development/component_ref/component_ref.md
Labels: cla:yes, size/S, priority/medium, kind/documentation, area/test, approved, lgtm

#869 chore: add demo code for delay queue API, using chatGPT
  demo/delay_queue/common/client.go
Labels: cla:yes, size/M, kind/demo, priority/low

#892 feat: change schedule time interval
  .github/workflows/kube-bot.yaml
Labels: size/XS, cla:yes, area/ci, approved, lgtm, priority/high

#898 fix: make format and update command guide docs
  docs/en/development/commands.md
  docs/zh/development/commands.md
  make/golang.mk
Labels: bug, cla:yes, size/S, First-time contributor, priority/medium, area/tools, approved, lgtm

#908 ci: run dead link checker when there are markdown files been modified
  .github/workflows/dead-link-checker.yaml
Labels: question, size/XS, cla:yes, approved, lgtm

#909 fix: optimize custom component initialization
  pkg/runtime/runtime.go
Labels: bug, cla:yes, size/S, area/component, approved, lgtm, area/optimization
