Repository mosn/layotto, pull requests merged in 2023-10, with the labels that each got.

#993 feat: support pod injection to deploy Layotto as a sidecar in Kubernetes
  .github/workflows/layotto-ci.yml
  .github/workflows/layotto-release.yml
  cmd/layotto_injector/main.go
  demo/state/k8s/Dockerfile
  demo/state/k8s/README.md
  demo/state/k8s/client.go
  demo/state/k8s/config.json
  demo/state/k8s/go.mod
  demo/state/k8s/go.sum
  demo/state/k8s/images/log.jpg
  demo/state/k8s/images/pods.jpg
  demo/state/k8s/state-sdk-demo.yaml
  deploy/charts/injector-helm/.helmignore
  deploy/charts/injector-helm/Chart.yaml
  deploy/charts/injector-helm/README.md
  deploy/charts/injector-helm/templates/NOTES.txt
  deploy/charts/injector-helm/templates/_helpers.tpl
  deploy/charts/injector-helm/templates/layotto_sidecar_injector_deployment.yaml
  deploy/charts/injector-helm/templates/layotto_sidecar_injector_service.yaml
  deploy/charts/injector-helm/templates/layotto_sidecar_injector_webhook_config.yaml
  deploy/charts/injector-helm/values.yaml
  docker/layotto_injector/Dockerfile
  go.mod
  go.sum
  make/common.mk
  make/helm.mk
  make/help.mk
  pkg/common/strings.go
  pkg/injector/annotations/annotations.go
  pkg/injector/consts/consts.go
  pkg/injector/patcher/patch.go
  pkg/injector/patcher/sidecar.go
  pkg/injector/patcher/sidecar_container.go
  pkg/injector/patcher/sidecar_patcher.go
  pkg/injector/patcher/sidecar_volumes.go
  pkg/injector/service/config.go
  pkg/injector/service/handle.go
  pkg/injector/service/handle_test.go
  pkg/injector/service/injector.go
  pkg/injector/service/pod_patcher.go
Labels: cla:yes, size/XXL, First-time contributor, approved, lgtm, priority/high, area/installation

#1006 fix: include checkout step for package laytto injector helm chart
  .github/workflows/layotto-ci.yml
  .github/workflows/layotto-release.yml
Labels: bug, size/XS, cla:yes

#1013 test: add ut for pkg/wasm
  pkg/mock/wasm/exports.go
  pkg/wasm/abi.go
  pkg/wasm/dispatch.go
  pkg/wasm/dispatch_test.go
  pkg/wasm/factory.go
  pkg/wasm/factory_test.go
  pkg/wasm/filter.go
  pkg/wasm/filter_test.go
  pkg/wasm/imports.go
  pkg/wasm/imports_test.go
  pkg/wasm/install/endpoint.go
  pkg/wasm/uninstall/endpoint.go
  pkg/wasm/update/endpoint.go
Labels: cla:yes, size/XXL
