Repository mosn/layotto, pull requests merged in 2023-06, with the labels that each got.

#935 feat: fix mongo lock panic
  components/lock/mongo/mongo_lock.go
Labels: bug, size/XS, cla:yes

#936 feat: Add extension conf in ApplicationContext
  pkg/grpc/context_generated.go
  pkg/runtime/context_generated.go
Labels: cla:yes, size/S

#947 feat: 更新钉群二维码,更改check配置文件,更新apollo,IP地址
  .github/dead_link_check_config.json
  README.md
  docs/en/component_specs/configuration/apollo.md
  docs/en/start/configuration/start-apollo.md
  docs/zh/blog/code/webassembly/index.md
  docs/zh/component_specs/configuration/apollo.md
  docs/zh/start/configuration/start-apollo.md
  docs/zh/start/file/minio.md
Labels: cla:yes, size/S, First-time contributor

#950 fix: 忽略Proxy WebAssembly Architecture 链接
  .github/dead_link_check_config.json
  docs/zh/blog/code/webassembly/index.md
Labels: bug, size/XS, cla:yes, approved

#906 docs: add go-sdk reference and supporting code cases.
  configs/config_standalone.json
  demo/file/local/client.go
  demo/go.mod
  demo/go.sum
  demo/hello/common/README.md
  demo/hello/common/client.go
  docs/en/sdk_reference/go/start.md
  docs/zh/sdk_reference/go/start.md
Labels: cla:yes, size/XXL, approved

#954 feat: Add metadata for s3
  components/oss/oss.go
  spec/proto/extension/v1/s3/oss.pb.go
  spec/proto/extension/v1/s3/oss.proto
  spec/proto/extension/v1/s3/oss_grpc.pb.go
Labels: cla:yes, size/XXL

#955 feat: unit test failed info more clear in ci
  make/golang.mk
Labels: cla:yes, size/S, First-time contributor, approved, lgtm

#939 feat: support nacos configstore component (level1)
  cmd/layotto/main.go
  cmd/layotto_multiple_api/main.go
  cmd/layotto_without_xds/main.go
  components/configstores/nacos/client.go
  components/configstores/nacos/config.go
  components/configstores/nacos/config_test.go
  components/configstores/nacos/configstore.go
  components/configstores/nacos/configstore_test.go
  components/configstores/nacos/const.go
  components/configstores/nacos/default_logger.go
  components/configstores/nacos/default_logger_test.go
  components/configstores/nacos/errors.go
  components/configstores/nacos/errors_test.go
  components/configstores/types.go
  components/go.mod
  components/go.sum
  components/pkg/mock/nacos_mock.go
  configs/config_nacos.json
  docs/_sidebar.md
  docs/en/component_specs/configuration/nacos.md
  docs/img/configuration/nacos/img.png
  docs/zh/_sidebar.md
  docs/zh/component_specs/configuration/nacos.md
  go.mod
  go.sum
  pkg/runtime/runtime.go
Labels: cla:yes, size/XXL
