Repository mosn/layotto, pull requests merged in 2023-08, with the labels that each got.

#978 feat: fix grpc trace
  components/trace/generator.go
  components/trace/generator_test.go
  diagnostics/genetator.go
  diagnostics/tracing.go
Labels: bug, cla:yes, size/S

#980 feat: fix huaweiyun obs convert
  components/oss/huaweicloud/oss.go
  components/oss/huaweicloud/oss_test.go
  components/oss/option.go
  components/oss/oss.go
  pkg/grpc/extension/s3/s3_test.go
Labels: bug, cla:yes, size/M

#982 feat: modify sms api proto
  docs/api/v1/sms.html
  spec/proto/extension/v1/sms/sms.pb.go
  spec/proto/extension/v1/sms/sms.proto
Labels: cla:yes, size/L
