Repository mosn/layotto, pull requests merged in 2023-07, with the labels that each got.

#957 docs: add nacos configstore component add quickstart document and docker-compose file.
  components/configstores/apollo/default_logger.go
  components/configstores/apollo/default_logger_test.go
  docker/layotto-nacos/config_nacos.json
  docker/layotto-nacos/docker-compose.yml
  docker/layotto-nacos/mysql.env
  docker/layotto-nacos/nacos-standlone-mysql.env
  docs/_sidebar.md
  docs/en/start/configuration/overview.md
  docs/en/start/configuration/start-nacos.md
  docs/img/configuration/nacos/layotto-nacos-configstore-component.png
  docs/zh/_sidebar.md
  docs/zh/start/configuration/overview.md
  docs/zh/start/configuration/start-nacos.md
  spec/proto/extension/v1/s3/oss.pb.go
  spec/proto/extension/v1/s3/oss_grpc.pb.go
Labels: cla:yes, size/L, approved, lgtm

#969 feat: fix cryption configure file
  components/cryption/aliyun/kms.go
  components/cryption/aws/kms.go
  configs/config_cryption.json
Labels: bug, cla:yes, size/S, approved, lgtm

#972 feat: fix client comments and add recover for s3 interface
  demo/cryption/client.go
  pkg/grpc/extension/s3/s3.go
Labels: bug, cla:yes, size/L

#971 feat: Implement the Email component based on Aliyun DM
  cmd/layotto/main.go
  components/email/aliyun/email.go
  components/email/aliyun/email_test.go
  components/email/errors.go
  components/email/meta.go
  components/go.mod
  components/go.sum
  configs/config_email_aliyun.json
  demo/email/client.go
  go.mod
  go.sum
Labels: cla:yes, size/L, approved, lgtm
