Repository mosn/layotto, pull requests merged in 2024-07, with the labels that each got.

#1055 feat: add NewVariableContext for StreamInterceptorFilter
  diagnostics/grpc_tracing.go
Labels: size/XS, cla:yes

#1058 feat: 贡献文档的修改||feat: Modification of the contribution document
  .github/ISSUE_TEMPLATE/good-first-issue-component.md
  .github/ISSUE_TEMPLATE/good-first-issue-go-demo.md
  .github/ISSUE_TEMPLATE/good-first-issue-java-demo.md
  .github/workflows/docusaurus-ci.yml
  README.md
  algolia-config.json
  crowdin.yaml
  demo/faas/code/assemblyscript/README.md
  demo/faas/code/rust/README.md
  docs/blog/code/layotto-rpc/index.md
  docs/blog/code/webassembly/index.md
  docs/docs/README.md
  docs/docs/building_blocks/rpc/reference.md
  docs/docs/development/contributing-doc.md
  docs/docs/development/developing-api.md
  docs/docs/development/start-from-zero.md
  docs/docs/sdk_reference/go/start.md
  docs/docs/start/faas/start.md
  docs/docusaurus.config.js
  docs/i18n/en-US/docusaurus-plugin-content-blog/code/layotto-rpc/index.md
  docs/i18n/en-US/docusaurus-plugin-content-blog/code/webassembly/index.md
  docs/i18n/en-US/docusaurus-plugin-content-docs/current/README.md
  docs/i18n/en-US/docusaurus-plugin-content-docs/current/building_blocks/rpc/reference.md
  docs/i18n/en-US/docusaurus-plugin-content-docs/current/development/contributing-doc.md
  docs/i18n/en-US/docusaurus-plugin-content-docs/current/development/developing-api.md
  docs/i18n/en-US/docusaurus-plugin-content-docs/current/development/start-from-zero.md
  docs/i18n/en-US/docusaurus-plugin-content-docs/current/sdk_reference/go/start.md
  docs/i18n/en-US/docusaurus-plugin-content-docs/current/start/faas/start.md
  docs/i18n/en-US/docusaurus-plugin-content-pages/index.md
  docs/src/pages/index.md
  docs/static/img/development/doc/img_10.png
  docs/static/img/development/doc/img_11.png
  docs/static/img/development/doc/img_12.png
  docs/static/img/development/doc/img_14.png
  docs/static/img/development/doc/img_8.png
  docs/static/img/development/doc/img_9.png
  spec/proto/runtime/v1/README.md
Labels: cla:yes, size/XL

#1059 fix: README问题图片修复||fix: README problem image fix
  README.md
Labels: bug, size/XS, cla:yes

#1062 feat: 1,统一移动静态网站配置到docs目录||feat: 1, Configure the mobile static website to the docs directory
  .github/workflows/docusaurus-ci.yml
  docs/algolia-config.json
  docs/crowdin.yaml
  docs/package-lock.json
  docs/package.json
Labels: cla:yes, size/XXL

#1063 feat: 删掉原来的文件||feat: Delete the original file
  algolia-config.json
  crowdin.yaml
  package-lock.json
  package.json
Labels: cla:yes, size/XXL
